packages/L10n/package.json

UX-464 🦄🐴 L10n version

---

packages/Button/package.json
packages/Heading/package.json
packages/Icon/package.json
packages/L10n/package.json
packages/Popover/package.json
packages/RawButton/package.json
packages/Spinner/package.json
packages/Stylers/package.json
packages/TestingHelpers/package.json
packages/Tokens/package.json
packages/helpers/package.json

UX-464 🦄🐴 trying to publish first version

---

packages/Button/package.json
packages/Heading/package.json
packages/Icon/package.json
packages/L10n/package.json
packages/Popover/package.json
packages/RawButton/package.json
packages/Spinner/package.json
packages/Stylers/package.json
packages/TestingHelpers/package.json
packages/Tokens/package.json
packages/helpers/package.json

UX-464 🦄🐴 I blowed up again :/

---

README.md
package.json
packages/Heading/tests/Heading.spec.js
packages/Input/tests/input.spec.js
packages/Popover/src/helpers/getPosition.js

Splitting readme between regular consumers and contributors
---
---
---

UX-465 🦄🐴 updating readme

---

packages/Input/package.json

input version

---

lerna.json

Adding extension ignore extension to lerna
---
---
---

Adding ignore lerna files

---

packages/Input/src/Input.styles.js

Fix this bug reported by Phil in Safari: https://github.com/acl-services/paprika/issues/83
Couldn't test in IE11 -- Storybook doesn't list any stories.
Before:
After:

ISSUE-83 Remove rule affecting placeholder text in Safari

---

packages/Heading/package.json

---
Add missing dependency
---
---

PD-12468 - Add missing stylers dependency

---

packages/SidePanel/package.json

/ 🦄.
fixing package name camel case format
---
---
---

UX-346 fixing sidepanel package name

---

package.json

/ 🦄.
small fix for missing dependencies and wrong version of componentat at package.json for the repo
---
---
---

UX-346 fixing small dependencies

---

packages/DatePicker/package.json

/ 🦄.
missing `main: index.js` on datepicker
---
---
---

UX-346 Adding main index

---

packages/DatePicker/package.json

the build process failed but all this was automatically published by lerna
revert package json sass broke the build process... :/ 
---
---
---

UX-346-revert-version

---

.storybook/assets/styles/common.styles.js
packages/Input/stories/Input.stories.js

Allison storybond

---

packages/Collapsible/README.md

UX-496 Fix capitalization

---

packages/Collapsible/package.json

UX-496 Fix react version and component version

---

packages/Popover/src/components/Trigger/Trigger.js

Add `a11yText` prop for `Popover.Trigger`
---
---

AD-4016 Add a11yText prop for popover trigger

---

packages/CollapsibleChecklists/src/components/Group/Group.styles.js
packages/CollapsibleChecklists/src/components/Item/Item.styles.js

Please make this version 0.1.1

PD-12487 Centre align the content of the labels

---

packages/Select/package.json
packages/Switch/package.json
packages/Textarea/package.json

Fix export issue on `Select`, `Switch` and `Textarea`
---
---

AN-7723 Fix export issues

---

packages/FormElement/src/FormElement.js
packages/Select/package.json
packages/Select/src/Select.js

1. Pass more props in `<FormElement />`
2. Fix `<Select />` dependency
---
---

AN-7723 Fix small issues in Select and Form Element

---

packages/DropdownMenu/README.md

To add a readme file to the dropdown component
---
---

Add dropdownMenu readme

---

packages/DropdownMenu/README.md

Fix title in DropdownMenu readme
---
---

fix dropdownMenu Readme title

---

packages/L10n/README.md

An 7742 l10n locales fix readme

---

packages/L10n/README.md

Our first user found the readme unclear, so improving it.

An 7742 l10n update readme

---

packages/Select/src/Select.js
packages/Select/stories/examples/Showcase.js

- Set `value` to optional
- Remove `selected` on placeholder `<option>` element
---
---

AN-7724 Fix select component warnings

---

packages/ProgressAccordion/src/ProgressAccordion.js
packages/ProgressAccordion/src/components/Indicator/Indicator.styles.js
packages/ProgressAccordion/src/components/Item/Item.js
packages/ProgressAccordion/src/components/Item/Item.styles.js
packages/ProgressAccordion/src/components/Responses/Item.js
packages/ProgressAccordion/src/components/Responses/Responses.js

Some styling tweaks + some `data-pka-anchors` added for testing.
- Font sizes are now more _resilient_ to global CSS (example `body { font-size: 14px; }`)
- **[PATCH UPDATE]**

PD-12544  ProgressAccordion touch ups 🐐

---

packages/Select/src/Select.styles.js

---
---
Before:
After:
<a href='http://storybooks.highbond-s3.com/paprika/AN-7732/Fix-select-styles-on-windows' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/AN-7732/Fix-select-styles-on-windows</a>

AN-7732 Fix default placeholder styling issue on windows

---

Dockerfile.build
Makefile

Add build files for the deployment pipeline.
---
---
---
<a href='http://storybooks.highbond-s3.com/paprika/UX-547-build-files' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/UX-547-build-files</a>

UX-547 Deploy paprika storybook master

---

packages/Popover/src/components/Tip/Tip.styles.js

Tiny fix for popover tip.
---
Before:
After:
<a href='http://storybooks.highbond-s3.com/paprika/AD-4104-Fix-popover-tip' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/AD-4104-Fix-popover-tip</a>

AD-4014 Fix popover style issue

---

packages/DropdownMenu/package.json
yarn.lock

Revert package version change for `DropdownMenu` component change in https://github.com/acl-services/paprika/pull/160
---
---
<a href='http://storybooks.highbond-s3.com/paprika/UX-541-Revert-dropdownMenu-version-change' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/UX-541-Revert-dropdownMenu-version-change</a>

ux-541-revert dropdown menu package changes

---

packages/DropdownMenu/README.md

Update readme for the DropdownMenu component
---
---
<a href='http://storybooks.highbond-s3.com/paprika/ux-541-dropdown-component-update-readme' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/ux-541-dropdown-component-update-readme</a>

ux-541-update-dropdown-readme

---

packages/L10n/README.md
packages/L10n/src/useI18n.js
packages/L10n/stories/L10n.stories.js
packages/L10n/stories/examples/withLocales/FakeAppWithLocales.js
packages/L10n/stories/examples/withLocales/Greeting.js

Merge custom locales and paprika locales together, updated story.
---
---
<a href='http://storybooks.highbond-s3.com/paprika/UX-563-Fix-custom-locales-issue' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/UX-563-Fix-custom-locales-issue</a>

UX-563 Fix custom locales issue

---

.prettierignore
README.md

---
Update readme with better content and more concise information.
View here for the readme file
https://github.com/acl-services/paprika/tree/UX-569-update-readme
---
---
<a href='http://storybooks.highbond-s3.com/paprika/UX-569-update-readme' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/UX-569-update-readme</a>

Ux 569 update readme

---

packages/DatePicker/src/DatePicker.js
packages/helpers/src/hooks/usePrevious.js

- Set default `humanFormat` using I18n
- Check if `date` changes in useEffect
---
---

UX-584 Fix date picker cannot type bug

---

packages/DropdownMenu/test/dropdownMenu.spec.js
packages/ListBox/package.json
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Divider/Divider.js
packages/ListBox/src/components/Option/Option.js
packages/ListBox/src/components/Option/helpers/optionState.js
packages/ListBox/src/components/Option/useIsSelectedOption.js
packages/ListBox/src/components/Options/helpers/options.js
packages/ListBox/src/hooks/hooks.js
packages/ListBox/src/store/actionTypes.js
packages/ListBox/src/store/reducer.js
packages/ListBox/stories/examples/multi.js
packages/ListBox/stories/examples/single.js
packages/ListBox/stories/fixtures/characters.js
packages/ListBox/stories/multi.stories.js
packages/ListBox/stories/single.stories.js
packages/ListBox/test/specs/multi/ListBox.multi.spec.js
packages/ListBox/test/specs/single/ListBox.single.spec.js
packages/helpers/src/dom/elementScrollToPolyfill.js
testingHelpers/config.js

Adding two new props to the ListBox *isSelected* and *defaultIsSelected*, given the ability to programmatically control the selected state of the`<ListBox />` in a more friendly way. 
*isSelected*: is a "controlled" prop that sync the internal state of the ListBox with the value passed down. 
*isDefaultSelected* is a uncontrolled prop and describe the initial state of the listbox at the moment of the first render.
---
The consumer is in charge of the `isSelected` controlled prop which synchronizes the internal state of the `ListBox`. But because a side effect could occur at the moment of selecting one or more options depending on the context, the onClick event still is not controlled, which means that even if the developer declares an onClick event on the Option itself, will not gain …

Ux 585 listbox improves

---

package.json
packages/DatePicker/src/DatePicker.js
packages/DatePicker/test/DatePicker.spec.js

Fix Date picker failing spec by setting specific time
@nahumzs minor bump
---
---

XD-5802-set datePicker date with Utc

---

packages/Sortable/README.md
packages/Sortable/src/Sortable.js
packages/Sortable/src/Sortable.styles.js
packages/Sortable/src/components/SortableItem/SortableItem.js
packages/Sortable/src/components/SortableItem/SortableItem.styles.js
packages/Sortable/stories/examples/Basic.js
packages/Sortable/stories/examples/Overflowing.scss
packages/Sortable/stories/examples/Screener.js

https://aclgrc.atlassian.net/browse/UX-568
Did not do the "Nice to have" or "Stretch" items.
Added hasZebraStripes prop:
Fixed overflow bug. Before:
After:
Changed `x` icon to a trashcan icon.

Ux 568 improve sortable

---

packages/Icon/src/ArrowUp.js
packages/Icon/src/svg/Arrow-Up.svg
packages/Icon/stories/examples/Test.js

Arrow up icon has incorrect sizing of 22 x 12
I have updated to be the same size as other icons being 24px x 24px
---
---

UX-594-update arrow up sizing

---

packages/Pill/package.json
packages/Pill/src/Pill.styles.js

---
---
- Alignment was off because I added an extra span inside the children that didn't have the align center
---
Before
After

PD-13496 fix alignment

---

packages/Button/src/Button.styles.js
packages/Button/src/ButtonKinds.js
packages/Button/stories/examples/Showcase.js

Fix Button styling for minor / flat kinds
Due to small typo here:
https://github.com/acl-services/paprika/pull/229/files#diff-e4b69523b9d8c8261be62809a61301b6L187
Before
After

UX-597 Fix Button styling for minor / flat kinds 🐐

---

packages/Button/src/Button.js
packages/Button/src/IconButton.js
packages/Heading/package.json
packages/Icon/package.json
packages/Input/package.json
packages/L10n/package.json
packages/ListBox/package.json
packages/Popover/package.json
packages/RawButton/package.json
packages/Spinner/package.json
packages/Toast/tests/Toast.spec.js
packages/Tokens/package.json

Ensure all react peer dependencies are at least set to `^16.8.0`
See https://github.com/acl-services/paprika/issues/225
---
1. Fixed some prop-types warning 
2. Fixed one unit-test warning
---
Warnings:

Fix peer deps

---

packages/SidePanel/src/components/Group/Group.styles.js
packages/SidePanel/src/components/Overlay/Overlay.js

PD-13509 fix group and overlay

---

packages/Counter/src/Counter.js

---
- fix proptype warning for counter
---
---

PD-13509 fix proptype error

---

packages/ListBoxBrowser/src/components/CustomListBox/CustomListBox.styles.js
packages/ListBoxBrowser/src/components/OptionsSelected/OptionsSelected.js
packages/ListBoxBrowser/src/components/OptionsSelected/OptionsSelected.styles.js
packages/ListBoxBrowser/src/components/Title/Title.styles.js

To fix minor styling changes such as font sizes, backgrounds, etc.
---
---
---

Ux 588 styling changes

---

packages/DatePicker/src/DatePicker.js
packages/DatePicker/stories/DatePicker.stories.js
packages/Popover/src/Popover.js

Resolves https://github.com/acl-services/paprika/issues/240
Update popover content position on children change. This to fix issues where the content of the popover isn't positioning itself in the right position sometimes or with right size.
---
---

Update popover content position based on child change

---

packages/SidePanel/src/components/Header/Header.styles.js

- due to side panel feedback we want to make the font size to 18px and bold for the header

PD-13523 change header side panel font and weight

---

packages/DatePicker/src/DatePicker.js
packages/DatePicker/src/DatePicker.styles.js
packages/DatePicker/src/components/Calendar/Calendar.js

Date Pickers usage of the Popover component has changed now that we have updated the way that the popover handles its child components. Side effect of https://github.com/acl-services/paprika/pull/249
This Pr aims to primarily fix the errors reported in failing jest test on Date Picker component
Additionally I have cleaned up the way we are rendering calendar, which now unmounts the component when it should not be visible.
---

Ux 271 fix date picker errors

---

packages/SidePanel/src/components/Header/Header.styles.js
packages/SidePanel/stories/SidePanel.Header.stories.js

PD-13719 fix purple header

---

packages/Popover/src/Popover.js
packages/Popover/src/components/Content/Content.js
packages/Popover/stories/Popover.stories.js
packages/Popover/stories/examples/FocusTest.js

Handle all the cases.
- Pick and choose this parts you like.

PD-13298 Tab focus logic adjustments (suggested) 🐐

---

packages/DataTable/src/DataTable.js
packages/DataTable/src/context.js
packages/DataTable/src/hooks/useAsyncReducer.js
packages/DataTable/src/reducers/sort.js
packages/DataTable/stories/BackendSort.stories.js

Clean version of https://github.com/acl-services/paprika/pull/293
---
---

Ux 645 data table async reducer

---

README.md

Simplify Paprika repo [README.md](https://github.com/acl-services/paprika/blob/UX-512--Update-README/README.md) and avoid redundancy between this document and the Contributing Guidelines.

UX-569 Update README 🐐

---

.github/PULL_REQUEST_TEMPLATE.md

_Jira ticket / GitHub issues_
---
- [Contributing Guidelines](https://github.com/acl-services/paprika/wiki/Contributing-Guidelines)
- [README](https://github.com/acl-services/paprika/blob/master/README.md)
- [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [Ask for help](https://github.com/acl-services/paprika/issues/new?template=help_wanted.md)

Updates to PR template 🐐

---

CODE_OF_CONDUCT.md
README.md

Add a [CODE_OF_CONDUCT.md](https://github.com/acl-services/paprika/blob/UX-512--code-of-conduct/CODE_OF_CONDUCT.md).

UX-512  Code of Conduct 🐐

---

packages/SidePanel/src/SidePanel.js
packages/SidePanel/src/components/Dialog/Dialog.js
packages/SidePanel/src/components/Dialog/Dialog.styles.js
packages/SidePanel/src/components/Group/Group.js
packages/SidePanel/src/components/Header/Header.js
packages/SidePanel/src/components/Header/Header.styles.js
packages/SidePanel/stories/SidePanel.Group.stories.js
packages/SidePanel/stories/SidePanel.Header.stories.js
packages/SidePanel/stories/SidePanel.Overlay.stories.js
packages/SidePanel/stories/SidePanel.stories.js

Address side panel tweaks based off of John's design tweaks #298 
- See Github Issue #298  for details.
-  ✅ MAJOR (breaking) change to _these packages_
http://storybooks.highbond-s3.com/paprika/UX-666-side-panel-tweaks
Resolves #298

Ux 666 side panel tweaks

---

packages/DataTable/src/DataTable.js
packages/DataTable/src/VirtualizeRows.js
packages/DataTable/src/VirtualizeRows.styles.js
packages/DataTable/src/components/Cell/Cell.js
packages/DataTable/src/components/Cell/Cell.styles.js
packages/DataTable/src/components/RowHeight/RowHeight.js
packages/DataTable/src/components/VirtualizedTable/VirtualizedTable.js
packages/DataTable/src/components/VirtualizedTable/VirtualizedTable.styles.js
packages/DataTable/src/context.js
packages/DataTable/src/helpers/handleArrowKeys.js
packages/DataTable/stories/BackendSort.stories.js
packages/DataTable/stories/DataTable.stories.js
packages/DataTable/stories/DataTableNavigation.stories.js
packages/DataTable/stories/DataTableTypes.stories.js
packages/DataTable/stories/DataTableWithSort.stories.js
packages/DataTable/stories/examples/Marvel/App.js
packages/DataTable/stories/examples/Marvel/Marvel.stories.js
packages/DataTable/stories/examples/Marvel/helpers.js
packages/DataTable/stories/helpers.js
packages/helpers/src/dom/closest.js

Prepare table to incorporate infintive scroll and load more.
http://storybooks.highbond-s3.com/paprika/ux-668-infinitive-scroll-load-more

Ux 668 infitive scroll load more

---

packages/DataTable/src/DataTable.js
packages/DataTable/src/components/ColumnDefinition/ColumnDefinition.js
packages/DataTable/src/components/Navigation/components/Sort/SortTrigger.js
packages/DataTable/src/components/Options/Options.js
packages/DataTable/src/components/Options/SortOption.js
packages/DataTable/src/components/VirtualizedTable/VirtualizedTable.js
packages/DataTable/src/constants.js
packages/DataTable/src/context.js
packages/DataTable/src/helpers/sort.js
packages/DataTable/stories/BackendSort.stories.js
packages/DataTable/stories/DataTableTypes.stories.js
packages/DataTable/test/helpers/sort.spec.js

Ux 652 Setting default type to string

---

packages/DropdownMenu/README.md
packages/DropdownMenu/src/DropdownMenu.js
packages/DropdownMenu/src/components/Trigger/Trigger.js
packages/DropdownMenu/stories/examples/DropdownMenuDisabledExample.js
packages/DropdownMenu/stories/examples/DropdownMenuDividersExample.js
packages/DropdownMenu/stories/examples/DropdownMenuExample.js
packages/DropdownMenu/stories/examples/DropdownMenuLongestExample.js
packages/DropdownMenu/stories/examples/DropdownMenuMultiConfirmationExample.js
packages/DropdownMenu/stories/examples/DropdownMenuTriggerExample.js
packages/DropdownMenu/stories/examples/Showcase.js
packages/DropdownMenu/test/dropdownMenu.spec.js

Simplify the trigger Api for the dropdownComponent
Secondary fixes include
- Added the edge property on dropdown component for alignment to the trigger
- Cleanup of the story knobs 
- Changed the Dropdown.Trigger component api to use `buttonType` prop allowing us to pass any content and set the button appearance.
- [x ] MAJOR (breaking) change to _these packages_
https://github.com/acl-services/paprika/issues/131_

Ux 131 dropdown api change

---

.github/PULL_REQUEST_TEMPLATE.md

Patch fixes don't have to be big 🗣

UX-346 typo in PR template

---

packages/DataTable/package.json
packages/DataTable/src/DataTable.js
packages/DataTable/src/components/ColumnDefinition/ColumnDefinition.js
packages/DataTable/src/components/Navigation/Navigation.js
packages/DataTable/src/components/Navigation/components/ColumnManaging/ColumnManaging.js
packages/DataTable/src/components/Navigation/components/ColumnManaging/ColumnManagingItem.js
packages/DataTable/src/components/Navigation/components/ColumnManaging/index.js
packages/DataTable/src/components/Navigation/components/Sort/Sort.js
packages/DataTable/src/components/Navigation/components/Sort/SortTrigger.js
packages/DataTable/src/components/Options/Options.js
packages/DataTable/src/components/Options/SortOption.js
packages/DataTable/src/components/RowHeight/RowHeight.js
packages/DataTable/src/components/VirtualizedTable/VirtualizedTable.js
packages/DataTable/src/constants.js
packages/DataTable/src/context.js
packages/DataTable/src/hooks/useAsyncReducer.js
packages/DataTable/src/reducers/table.js
packages/DataTable/stories/ShowHideColumns.stories.js
packages/DataTable/stories/examples/Marvel/App.js
packages/DataTable/test/AsyncData.cypress.js
packages/DataTable/test/ShowHideColumns.cypress.js
packages/DataTable/test/ToggleRowHeight.cypress.js
packages/DropdownMenu/src/DropdownMenu.js
yarn.lock

Show/hide columns
http://storybooks.highbond-s3.com/paprika/UX-646-show-hide-columns

UX-646 Show and hide columns

---

packages/Sortable/src/components/SortableItem/SortableItem.styles.js

- update this to match the same values as the pill component: text: 3F3D3C, background:D7D7D7,using tokens.
-resolves https://github.com/acl-services/paprika/issues/222
@oscarkwan 
BEFORE
AFTER

Sortable a11y-resolves #222

---

packages/Button/src/IconButton.styles.js

- simply hard-code the font sizes for the icons into the t-shirt size variables in IconButton.styles.js
- resolves https://github.com/acl-services/paprika/issues/307
@oscarkwan @johnpeele @nahumzs 
http://storybooks.highbond-s3.com/paprika/os-icon_button

change font size hard-code

---

packages/Takeover/src/components/Content.js
packages/Takeover/src/components/Header.js
packages/Takeover/src/components/Header.styles.js
packages/Takeover/stories/Takeover.stories.js
packages/Tokens/src/tokens.yaml

Some design tweaks for Takeover component requested by @johnpeele 
Resolves #295 
http://storybooks.highbond-s3.com/paprika/UX-663-takeover-design-tweaks
**Before:**
**After:**
https://aclgrc.atlassian.net/browse/UX-663
https://github.com/acl-services/paprika/issues/295

UX-663 Takeover design tweaks

---

README.md

Revisions to Accessibility section of README.

UX-512 Update a11y details in README 🐐

---

packages/L10n/src/locales-js/de.js
packages/L10n/src/locales-js/en.js
packages/L10n/src/locales-js/es.js
packages/L10n/src/locales-js/fr.js
packages/L10n/src/locales-js/ja.js
packages/L10n/src/locales-js/pl.js
packages/L10n/src/locales-js/pt.js
packages/L10n/src/locales-js/zh.js
packages/L10n/src/locales/de.yml
packages/L10n/src/locales/en.yml
packages/L10n/src/locales/es.yml
packages/L10n/src/locales/fr.yml
packages/L10n/src/locales/ja.yml
packages/L10n/src/locales/pl.yml
packages/L10n/src/locales/pt.yml
packages/L10n/src/locales/zh.yml

Fix typo in en.yml translations file. 
Manually update the type error key in all other language yml files and ran script to generate new js files

ux-131-fix typo in yml

---

packages/DataTable/src/DataTable.js
packages/DataTable/src/components/Navigation/components/ColumnManaging/ColumnManaging.js
packages/DataTable/src/components/Navigation/components/ColumnManaging/ColumnManagingItem.js
packages/DataTable/src/components/Navigation/components/Sort/Sort.js
packages/DataTable/src/components/VirtualizedTable/VirtualizedTable.js
packages/DataTable/src/context.js
packages/DataTable/test/ShowHideColumns.cypress.js
packages/DataTable/test/SortableDataTable.cypress.js

- Only copy over configurations into contexts for ColumnDefinition
- Minor prop-type checking fix
Demo

UX-633 Fix columns context issue

---

packages/Confirmation/README.md

Update readme for confirmation component
http://storybooks.highbond-s3.com/paprika/xd-7194-update-confirmation-component-readme

Update readme for confirmation component

---

packages/DataTable/src/DataTable.js
packages/DataTable/src/components/ColumnDefinition/ColumnDefinition.js
packages/DataTable/src/components/Navigation/components/Filters/FilterItem.js
packages/DataTable/src/components/Navigation/components/Filters/Filters.js
packages/DataTable/src/components/Options/Options.js
packages/DataTable/stories/DataTableRowIndicator.stories.js

Star 36 fix widgets with row indicator

---

packages/Confirmation/src/Confirmation.js
packages/Confirmation/src/components/TriggerButton/TriggerButton.js
packages/Counter/src/Counter.js
packages/Input/src/Input.js
packages/ListBox/src/components/Divider/Divider.js
packages/Pill/src/Pill.js
packages/RawButton/src/RawButton.js
packages/Select/src/Select.js
packages/SidePanel/src/components/FocusTrap/FocusTrap.js
packages/SidePanel/src/components/Group/Group.js
packages/Spinner/src/Spinner.js
packages/Switch/src/Switch.js
packages/Tabs/src/components/List/List.js
packages/Tabs/src/components/Panel/Panel.js
packages/Tabs/src/components/Tab/Tab.js
packages/Textarea/src/Textarea.js
packages/Toast/src/Toast.js
packages/Uploader/src/Uploader.js

-Add any missing data-pka-anchors to components that do not have any.
_Added data-pka-anchors in components but please let me know if I miss any components. 
@oscarkwan 
http://storybooks.highbond-s3.com/paprika/os-add-data-pka-anchor

Add missing data-pka-anchors to components

---

packages/Modal/package.json
packages/Modal/src/Modal.js
packages/Modal/src/Modal.styles.js
packages/Overlay/package.json
packages/Overlay/src/Overlay.js
packages/Takeover/package.json
packages/Takeover/stories/Takeover.stories.js
yarn.lock

Resolves #351 
http://storybooks.highbond-s3.com/paprika/STAR-54-replace-focus-trap-lib
https://aclgrc.atlassian.net/browse/STAR-54

STAR-54 Replace focus-trap-react with react-focus-lock

---

packages/Modal/src/Modal.styles.js
packages/Stylers/src/helpers.js
packages/Stylers/src/helpers.scss
packages/Stylers/src/includes.js
packages/Stylers/stories/helpers.scss
packages/Stylers/stories/sass-helpers.stories.js
packages/Stylers/stories/stylers.stories.js
packages/Stylers/stories/stylers.stories.styles.js
packages/Tokens/src/tokens.yaml

Add a new "subtle" focus indicator style to the `<Modal>` component's scrollable content container.
- Added new token: `highlight.active.nonInteractive.outline`.
- Focus indicator token names are too long to remember, and sometimes additional rules are needed with them, so I've created new `stylers` (includes / mixins) with the following names in JS:
- `stylers.focusRing` (also works as `stylers.focusRing()`)
- `stylers.focusRing(true)` (the argument is for `inset` style)
- `stylers.focusRing.bordered`
- `stylers.focusRing.bordered(true)`
- `stylers.focusRing.subtle` (this is the new one for "non-interactive" elements)
- `stylers.focusRing.subtle(true)`
And in Sass:
- `focus-ring`
- `focus-ring(true)`
- `focus-ring--bordered`
- `focus-ring--bordered(true)`
- `focus-ring--subtle`
- …

STAR-59  Modal content focus indicator 🐐

---

.semaphore/semaphore.yml
packages/Button/test/Button.spec.js

- add semaphore config to auto cancel builds if new commit is pushed, except for master

UX-709 add auto cancel config in semaphore

---

README.md

Update README with consideration for the new [Using Paprika](https://github.com/acl-services/paprika/wiki/Using-Paprika) wiki pages.
https://aclgrc.atlassian.net/browse/STAR-4

STAR-4 Update README 🐐

---

packages/L10n/src/locales-js/en.js
packages/L10n/src/locales/en.yml
packages/ListBox/package.json
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Divider/Divider.js
packages/ListBox/src/components/Filter/Filter.js
packages/ListBox/src/components/Trigger/Trigger.js
packages/ListBox/src/helpers/DOMAttributes.js
packages/ListBox/test/cypress/ListBox.cypress.js

- Add a11y improvements and fixes
- Add i18n for listbox
http://storybooks.highbond-s3.com/paprika/PD-13961-fix-listbox-trigger-a11y

PD-13961 add a11y fixes and i18n to listbox

---

packages/SidePanel/src/SidePanel.js
packages/SidePanel/src/components/Dialog/Dialog.js
packages/SidePanel/src/components/Dialog/Dialog.styles.js
packages/SidePanel/stories/SidePanel.stories.js

- Add option to slide panel from the left side
http://storybooks.highbond-s3.com/paprika/UX-718-sidepanel-slide-direction

UX-718 slide from left sidepanel

---

packages/FormElement/src/components/Label/Label.styles.js
packages/L10n/src/locales-js/de.js
packages/L10n/src/locales-js/es.js
packages/L10n/src/locales-js/fr.js
packages/L10n/src/locales-js/ja.js
packages/L10n/src/locales-js/pl.js
packages/L10n/src/locales-js/pt.js
packages/L10n/src/locales-js/zh.js

In projects the `font-size` is override by bootstrap 

PD-14328 Fix form element label font-size

---

packages/ListBox/package.json
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Filter/Filter.js
packages/ListBox/src/components/Filter/Filter.styles.js
packages/ListBox/src/components/Option/Option.js
packages/ListBox/src/components/Option/Option.styles.js
packages/ListBox/src/components/Trigger/Trigger.js
packages/ListBox/src/components/Trigger/Trigger.styles.js
packages/ListBox/src/store/Provider.js

Adding `size` prop into listbox component
http://storybooks.highbond-s3.com/paprika/PD-14328-Add-sizes-for-listbox
Small:
Medium:
Large:

PD-14328 Add size prop on listbox

---

packages/SidePanel/src/SidePanel.js
packages/SidePanel/src/components/Dialog/Dialog.js
packages/SidePanel/src/components/Dialog/Dialog.styles.js
packages/SidePanel/src/components/Header/Header.js
packages/SidePanel/src/components/Header/Header.styles.js

- add a border depending on if there if content is pushed, otherwise always have box shadow
- for the header, we only want to display a border if the header is primary, and if content is pushed, otherwise no border. This is because border with primary header looks a bit off.
http://storybooks.highbond-s3.com/paprika/PD-14511-fix-sidepanel

PD-14511 add border color for sidepanel

---

packages/DialogActions/package.json
packages/DialogActions/src/DialogActions.js
packages/DialogActions/src/DialogActions.styles.js

Fix dependency in dialog actions
http://storybooks.highbond-s3.com/paprika/PD-14326-fix-dialog-actions-dependency

PD-14326 Fix dialog actions dependency

---

packages/DataGrid/src/DataGrid.js

- testing is this fixes an issue with datagrid when integrating inside projects

PD-14391 test if this works

---

packages/DataGrid/src/DataGrid.js

- lazy import mouse wheel package

PD-14391 lazy import mousewheel

---

packages/Button/src/Button.styles.js
packages/Button/src/LinkButton.js
packages/Button/stories/examples/Basic.js

PD-14332 Adding icon in link button, changing default kind on Link button

PD-14332 Adding icon in link button

---

packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Option/useIsSelectedOption.js
packages/ListBox/src/components/Options/Options.js
packages/ListBox/src/hooks/hooks.js
packages/ListBox/src/store/reducer.js

/ 🦄.
fixes https://github.com/acl-services/paprika/issues/447
fixing ListBox is always open when preselecting option when is multi.

STAR-177 bug(ListBox) Fixing isOpen controlled property

---

.gitignore
.prettierignore
packages/ListBox/src/components/Content/Content.js
packages/ListBox/src/components/Trigger/Trigger.js

The onchange was not triggered by the keyboard, this fix that
http://storybooks.highbond-s3.com/paprika/STAR-179-onchange-onkeyboard/?path=/story/listbox-single--onchange-listbox

Star 179 onchange onkeyboard

---

packages/Modal/README.md
packages/SidePanel/readme.md
packages/Takeover/README.md

Add a note about handling focus issues

ISSUE-453 Add a note about handling focus issues

---

packages/DataGrid/src/DataGrid.styles.js
packages/Tokens/src/tokens.yaml

- update token
http://storybooks.highbond-s3.com/paprika/STAR-219-update-color-table

STAR-219 update table header token and datagrid

---

.storybook/config.js
packages/Collapsible/stories/Collapsible.Tests.stories.js
packages/Collapsible/stories/Collapsible.backyard.stories.js
packages/Collapsible/stories/Collapsible.stories.js
packages/Collapsible/stories/Collapsible.stories.mdx
packages/Collapsible/stories/examples/Showcase.js
packages/Collapsible/stories/examples/Variations.js
packages/CollapsibleText/stories/CollapsibleText.Tests.stories.js
packages/CollapsibleText/stories/CollapsibleText.stories.mdx
packages/CollapsibleText/stories/examples/Showcase.js
packages/CollapsibleText/stories/examples/Variations.js
packages/DialogActions/stories/DialogActions.Tests.stories.js
packages/DialogActions/stories/DialogActions.mdx
packages/DialogActions/stories/DialogActions.stories.js
packages/DialogActions/stories/DialogActions.stories.mdx
packages/ProgressAccordion/stories/ProgressAccordion.stories.js
packages/SidePanel/stories/SidePanel.stories.js
packages/SidePanel/stories/SidePanel.stories.mdx
packages/Toast/stories/Toast.Tests.stories.js
packages/Toast/stories/Toast.backyard.stories.js
packages/Toast/stories/Toast.mdx
packages/Toast/stories/Toast.stories.js
packages/Toast/stories/Toast.stories.mdx

- add showcase and some storybook component format
http://storybooks.highbond-s3.com/paprika/UX-724-collapsible-stories

UX-724 collapsible stories

---

packages/Select/CHANGELOG.md
packages/Select/src/Select.js

Add aria-invalid to select component
http://storybooks.highbond-s3.com/paprika/ux-743-select-aria-invalid

UX-743 add aria-invalid to select

---

packages/Modal/CHANGELOG.md
packages/Modal/package.json

Bump modal component version for cleaned up lib files
http://storybooks.highbond-s3.com/paprika/ux-526-bump-modal-component-version

ux-526 bump modal version

---

packages/ListBox/package.json
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Trigger/Trigger.js
packages/ListBox/src/hooks/hooks.js
yarn.lock

the hook `useChildrenLengthChange ` is wrong for updating the `options` in the state, cause sometimes there might be options got updated, but remained the same number of them. This probably not the best way to do, but we want to solve the issue in people scheduler as soon as possible
http://storybooks.highbond-s3.com/paprika/SNP-182-fix-listbox

Snp 182 fix listbox

---

packages/DataGrid/src/DataGrid.js
packages/DataGrid/src/DataGrid.styles.js
packages/DataGrid/src/components/Cell/Cell.js
packages/DataGrid/stories/DataGrid.screener.js
packages/DataGrid/stories/DataGrid.zebra.stories.js

Adding zebra support to the DataGrid
http://storybooks.highbond-s3.com/paprika/STAR-240-DataGrid-zebra

STAR-240 adding zebra support - chore(DataGrid)

---

packages/DataGrid/src/components/ColumnDefinition/ColumnDefinition.js

Improve a console warning about bad prop types.
http://storybooks.highbond-s3.com/paprika/tiny-fix-datagrid-props-warning

Improve console warning

---

packages/DataGrid/CHANGELOG.md
packages/DataGrid/src/DataGrid.js

- fix keyboard navigation
- add changelog
http://storybooks.highbond-s3.com/paprika/STAR-239-fix-datagrid

STAR-239 fix keybaord navigation

---

packages/ListBox/src/components/Label/Label.js
packages/ListBox/src/components/Label/Label.styles.js

STAR-247 Fix listbox placeholder style

---

packages/DataGrid/CHANGELOG.md

STAR-248-adding-changelog

---

packages/Overlay/CHANGELOG.md
packages/Overlay/src/Overlay.js

Adding a `container` prop for `<Overlay>` to support special portal

ADM-414 Adding container prop for Overlay

---

packages/DataGrid/CHANGELOG.md
packages/DataGrid/src/DataGrid.styles.js
packages/DataGrid/stories/DataGrid.borderTypes.stories.js

quick fix 
changing values for DataGrid.types.VERTICAL and DataGrid.types.HORIZONTAL

Star 241 borders switch horizontal verticals

---

packages/DataGrid/src/DataGrid.js
packages/DataGrid/src/DataGrid.styles.js

/ 🦄.
Please approve it a soon as you have time :), we were missing the polyfill for IE for the DataGrid, and I fixed the issue in all browsers of the white spot, I think from style perspective the DataGrid its almost 👍 
cc @oscarkwan @mikrotron 
http://storybooks.highbond-s3.com/paprika/STAR-241-adding-polyfill

STAR-241 bug(DataGrid) this is required for IE version

---

packages/ActionBar/src/hooks/useSort/sort.js
packages/L10n/src/locales/en.yml

- Add missing translation for ActionBar.Sort SINGLE_SELECT
- Add compareFunctions for SINGLE_SELECT (sort A-Z, Z-A)

UXD-43 Fix ActionBar Sort SINGLE_SELECT

---

packages/DateInput/src/DateInput.js
packages/DatePicker/stories/DatePicker.stories.js
packages/DatePicker/test/DatePicker.cypress.js

Support date time in date-picker
http://storybooks.highbond-s3.com/paprika/STAR-263-support-date-time-in-datepicker

STAR-263 Support date time in date-picker

---

packages/DatePicker/src/components/DateInputPropsCollector/DateInputPropsCollector.js
packages/DatePicker/stories/DatePicker.stories.js
packages/ListBox/src/components/Trigger/Trigger.js
packages/ListBox/src/components/Trigger/Trigger.styles.js
packages/ListBox/stories/Trigger.stories.js

- add clearIcon to datepicker input and listbox trigger

PDTVT-337 add clear to listbox trigger and dateinput

---

packages/Input/src/Input.js

PDTVT-337 fix warning

---

packages/TimePicker/src/TimePicker.js

UXD-15 feature(TimePicker) quick fix

---

packages/ListBox/src/components/Footer/Footer.js

- add a prop to add extra buttons to listbox footer

Pdtvt 337 add listbox extra button

---

packages/Toast/CHANGELOG.md
packages/Toast/src/Toast.js

On Toast component provide a focus method on imperative api.
Fix close button not rendering correctly in consuming applications with acl-ui 3
This allows for setting focus in results questionnaires as part of https://aclgrc.atlassian.net/browse/TW-69
http://storybooks.highbond-s3.com/paprika/tw-464-toast-focus-imperative-api
https://aclgrc.atlassian.net/browse/TW-464

tw-464-toast-imperative-api

---

packages/FormElement/CHANGELOG.md
packages/FormElement/src/components/Content/Content.styles.js
packages/FormElement/src/components/Instructions/Instructions.styles.js

Fix form element spacing https://aclgrc.atlassian.net/browse/UXD-80
Without instruction:
With instruction:

UXD-27 Fix form element spacing

---

packages/TimePicker/src/TimePicker.js
packages/TimePicker/src/TimePicker.styles.js
packages/TimePicker/src/components/Picker/Picker.js
packages/TimePicker/src/components/Picker/Picker.styles.js
packages/TimePicker/stories/TimePicker.stories.js

UXD-65 Time picker refactor

---

packages/ListBox/CHANGELOG.md
packages/ListBox/src/components/Label/Label.js
packages/ListBox/src/components/Trigger/Trigger.js

support custom label in listbox
`<Label />` component calculates the text based on the `options` in the store. However, in some cases, the `options` doesn't have all the values.

UXD-131 support custom label in listbox

---

packages/Icon/README.md

Add Readme file to Icon component
http://storybooks.highbond-s3.com/paprika/UXD-136

UXD-136 Add Icon Readme

---

packages/Pagination/src/Pagination.styles.js
packages/Pagination/src/components/CurrentPageItem/CurrentPageItem.styles.js
packages/Pagination/src/components/EllipsisItem/ElipsisItem.styles.js
packages/Pagination/src/components/PageItem/PageItem.styles.js

Polish the Pagination component.
Added alignment to all items.
http://storybooks.highbond-s3.com/paprika/UXD-140-Pagination-polish-alignment
N/A

UXD-140 Pagination - Polish - Alignment

---

packages/Pagination/README.md
packages/Pagination/src/Pagination.js
packages/Pagination/src/components/PageItem/PageItem.js

Polish the Pagination component.
Add default onChange value
http://storybooks.highbond-s3.com/paprika/UXD-140-Pagination-polish-onchange
N/A
N/A

UXD-140 Pagination - Polish - set default for OnChange

---

packages/TimePicker/CHANGELOG.md
packages/TimePicker/src/TimePicker.js

Fix time picker icon dependency

UXD-147 Fix time picker icon dependency

---

packages/Pagination/CHANGELOG.md
packages/Pagination/src/components/ArrowItem/ArrowItem.styles.js
packages/Pagination/src/components/CurrentPageItem/CurrentPageItem.styles.js
packages/Pagination/src/components/EllipsisItem/ElipsisItem.styles.js
packages/Pagination/src/components/PageItem/PageItem.styles.js
packages/Pagination/src/components/Wrapper/Wrapper.styles.js

Resolve QA fail. 
- Adjusted font size to match Figma designs.
- Adjust spacing to match Figma designs.
http://storybooks.highbond-s3.com/paprika/UXD-148-Pagination-font-error
https://aclgrc.atlassian.net/browse/UXD-148

UXD-148 Pagination Adjusted Font Size and Spacing

---

README.md

Updating pills

---

packages/Overlay/src/Overlay.styles.js

Refactor styling for Overlay component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-201-refactor-styling-Overlay
N/A

UXD-201 Style: refactor Overlay

---

packages/ProgressAccordion/src/ProgressAccordion.js
packages/ProgressAccordion/src/ProgressAccordion.styles.js
packages/ProgressAccordion/src/components/Indicator/Indicator.js
packages/ProgressAccordion/src/components/Indicator/Indicator.styles.js
packages/ProgressAccordion/src/components/Item/Item.js
packages/ProgressAccordion/src/components/Item/Item.styles.js
packages/ProgressAccordion/src/components/Responses/Responses.js
packages/ProgressAccordion/src/components/Responses/Responses.styles.js

To refactor the styling for the ProgressAccordion component.
NA
http://storybooks.highbond-s3.com/paprika/UXD-203-refactor-styling-ProgressAccordion
N/A

UXD 203 refactor styling progress accordion

---

packages/ListBox/index.d.ts

UXD-151 chore(ListBox) updating d.ts file

---

packages/Counter/src/Counter.styles.js

To resolve UI issues. Specifically the sizes were not adjusting properly.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-223-refactor-styling-Counter-fail
https://aclgrc.atlassian.net/browse/UXD-223

UXD-223 Refactor Counter Styling Issue

---

packages/Tabs/src/components/List/List.js
packages/Tabs/src/components/List/List.styles.js
packages/Tabs/src/components/Panel/Panel.js
packages/Tabs/src/components/Panel/Panel.styles.js
packages/Tabs/src/components/Tab/Tab.js
packages/Tabs/src/components/Tab/Tab.styles.js

Refactor styling for the Tabs component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-219-refactor-styling-Tabs
N/A

UXD-219 Refactor styling Tabs

---

packages/Spinner/src/Spinner.js
packages/Spinner/src/Spinner.styles.js

Refactor styling for the Spinner component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-217-refactor-styling-Spinner
N/A

UXD-217 Refactor styling Spinner

---

packages/Sortable/src/Sortable.js
packages/Sortable/src/Sortable.styles.js

Refactor styling for the Sortable component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-216-refactor-styling-Sortable
N/A

UXD-216 Refactor styling Sortable

---

packages/Switch/src/Switch.js
packages/Switch/src/Switch.styles.js

Refactor styling for the Switch component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-218-refactor-styling-Switch
N/A

UXD-218 Refactor styling Switch

---

packages/SidePanel/src/components/Trigger/Trigger.js
packages/Takeover/src/Takeover.js
packages/Takeover/src/Takeover.styles.js
packages/Takeover/src/components/Header/Header.js
packages/Takeover/src/components/Header/Header.styles.js
packages/Takeover/stories/Takeover.stories.js

Refactor styling for the Takeover component.
N/A
http://storybooks.highbond-s3.com/paprika/UXD-220-refactor-styling-Takeover
N/A

UXD-220 Refactor styling Takeover

---

packages/ProgressBar/README.md
packages/ProgressBar/src/index.d.ts

running npm lerna bootstrap

---

yarn.lock

chore: sync yarn.lock

---

packages/DataGrid/src/DataGrid.styles.js
packages/Table/CHANGELOG.md
packages/Table/README.md
packages/Table/src/Table.js
packages/Table/stories/Table.stories.js
packages/Table/tests/cypress/Table.cypress.js

To align DataGrid and Table designs with the designs in the Figma Starling UI Kit.
- Re-arranged the zebra pattern on DataGrid 
- Changed default borders for the Table component
http://storybooks.highbond-s3.com/paprika/UXD-316-DataGrid-Table-zebra-order
DataGrid Before:
DataGrid After:
Table Before:
Table After:
https://aclgrc.atlassian.net/browse/UXD-316

UXD-316 DataGrid & Table zebra order

---

.semaphore/release.yml

UXD-425 Try running semaphore

---

.npmrc
.semaphore/release.yml

UXD-425 Fix git

---

.semaphore/release.yml
packages/TimePicker/README.md
packages/TimePicker/src/index.d.ts

UXD-425 Add user name and email

---

.gitignore

UXD-425 Add npmrc in to gitignore

---

.semaphore/release.yml

UXD-476 Add npm dist tag for prerelease

---

package.json
scripts/commit-validator.js

In the Commit Validator:
- refactor
- Improve error messages
- support commas and spaces in "scope" section
- only inject ticketId if its not in there already

Uxd 409 error message improvements

---

README.md

Add several NPM shields for new components.

STAR-236 Update NPM shields 🐐

---

.npmrc
yarn.lock

UXD-507 Remove npmrc

---

yarn.lock

Update yarn.lock with newly moved packages

chore(ListBox): UXD-497 update yarn file so component deploys

---

README.md

This doesn't touch any code is just a readme change

OS-update-package-names-README

---

scripts/rename-package.js

Add more descriptive instructions in rename script

chore(RenameScript): UXD-494 Improve instructions

---

README.md
packages/ActionBar/tests/cypress/ActionBar.cypress.js
packages/Button/stories/Button.stories.mdx
packages/ExternalLink/README.md
packages/ExternalLink/src/ExternalLink.js
packages/ExternalLink/src/index.d.ts
packages/Heading/stories/Heading.stories.mdx
packages/Heading/stories/examples/Showcase.js
packages/RawButton/stories/RawButton.backyard.stories.js
packages/RawButton/stories/RawButton.stories.js
packages/RawButton/stories/RawButton.stories.mdx
packages/RawButton/stories/examples/OldRef.js
packages/RawButton/stories/examples/Showcase.js
packages/RawButton/stories/examples/Variations.js
yarn.lock

- refactor rawbutton stories
- change `ExternalLink` ariaText to a11yText
- fixed typo
- added docs / showcase / variations to rawbutton
- refactor to use story format
http://storybooks.highbond-s3.com/paprika/UXD-485-raw-button-docs
https://aclgrc.atlassian.net/browse/UXD-485

UXD-485 raw button stories refactor

---

packages/Popover/src/index.d.ts
scripts/typesFiles.js

remove `const null: any;` in popover .d.ts

fix(Popover): UXD-550 type issue

---

packages/ListBoxBrowser/src/ListBoxBrowser.js

ListBox-Broswer verison incompatibility in npm, this will force change the version.

OS-fixing-publish

---

yarn.lock

chore(Paprika): update lock file

---

packages/ActionBar/src/components/SearchInput/SearchInput.js
packages/ActionBar/stories/ShowcaseApp/ShowcaseApp.js
packages/StatusTracker/src/StatusTracker.js

- Added action bar search input debounce dependencies
- Passed more props into the ol element in status tracker

UXD-470 minor fixes for StatusTracker and ActionBar

---

README.md

update readme on enforcing conventional commits

docs(Paprika): UXD-409 update readme on enforcing conventional commits

---

README.md

No Jira ticket – no code changes.

Add Semaphore build status shield to README 🐐

---

packages/ListBox/stories/WithTags/examples/CustomTrigger.js
packages/ListBox/stories/WithTags/examples/UncontrolledUser.js

Fix ListBoxWithTags stories
Two stories on prod were broken because of bad props (caused by recent changes):
https://paprika.highbond.com/?path=/story/forms-listbox--list-box-with-tags-uncontrolled-with-custom-trigger
https://paprika.highbond.com/?path=/story/forms-listbox--list-box-with-tags-uncontrolled-users
http://storybooks.highbond-s3.com/paprika/uxd-588--fix-uncontrolled-list-box

fix(ListBox): UXD-588 Provide proper props to Avatar component stories

---

packages/ListBox/src/index.d.ts

docs(ListBox): UXD-590 Update type defs

---

.semaphore/release.yml
.semaphore/semaphore.yml
packages/DataGrid/tests/DataGrid.cypress.js

chore(Paprika): UXD-704 add swapfile before all jobs

---

.gitignore
README.md
package.json
packages/helpers/src/licence.js
packages/helpers/src/license.js
yarn.lock

Script that outputs a licence.xls listing all the dependencies for our project with their respective licence attached to it. 

chore(Paprika): UXD-762 adding licence support

---

packages/DynamicHyperlinkTransformer/package.json

I renamed `DynamicHyperlink` to `DynamicHyperlinkTransformer`, so had to change the version back to 0.0.1 for the release.

chore(DynamicHyperlink): PDTVT-753 change version for release

---

packages/DynamicHyperlinkTransformer/src/DynamicHyperlinkTransformer.js

Removed the timeout and made it work like this:
1. process the links on the DOM
2. process the links in each ckEditor when it is ready

refactor(DynamicHyperlinkTransform): PDTVT-753 Dont use a setTimeout

---

packages/DynamicHyperlinkTransformer/stories/examples/Showcase.js

Add locale to story for DynamicHyperlinkTransformer
http://storybooks.highbond-s3.com/paprika/pdtvt-745--add-l10n-to-story

chore(DynamicHyperlinkTransformer): PDTVT-745 Add locale to story

---

packages/Table/src/index.d.ts

chore(Paprika): UPDATE-files update files

---

packages/StatusTracker/CHANGELOG.md
packages/StatusTracker/src/components/Point/Point.styles.js

Changing white to green 😄  and we don't need the hover state anymore

feat(StatusTracker): SNP-1125 update color

---

packages/seducer/CHANGELOG.md
packages/seducer/package.json

adding lib/index in package.json

feature(seducer): UXD-630 fixing package issue

---

packages/seducer/package.json

feature(seducer): UXD-630 reverting package version

---

packages/L10n/src/locales/de.yml
packages/L10n/src/locales/es.yml
packages/L10n/src/locales/fr.yml
packages/L10n/src/locales/ja.yml
packages/L10n/src/locales/pt.yml
packages/L10n/src/locales/zh.yml

L10N-315 2021-02-12-25534 - translations batch

---

packages/ListBox/stories/ListBox.backyard.stories.js
packages/ListBox/stories/ListBox.single.stories.js

- fix broken source links
**No change to source code**
http://storybooks.highbond-s3.com/paprika/UXD-846-broken-links

UXD-846 docs(ListBox): fix broken links

---

packages/Panel/README.md
packages/Panel/src/index.d.ts

updating the auto generated docs to unblock pre-release

docs(Panel): UXD-820 update doc

---

packages/L10n/src/locales/de.yml
packages/L10n/src/locales/es.yml
packages/L10n/src/locales/fr.yml
packages/L10n/src/locales/ja.yml
packages/L10n/src/locales/pt.yml
packages/L10n/src/locales/zh.yml

L10N-315 2021-02-18-29973 - translations batch

---

packages/L10n/src/locales/de.yml
packages/L10n/src/locales/es.yml
packages/L10n/src/locales/fr.yml
packages/L10n/src/locales/ja.yml
packages/L10n/src/locales/pt.yml
packages/L10n/src/locales/zh.yml

L10N-315 2021-02-25-5690 - translations batch

---

packages/CollapsibleCard/package.json
packages/CollapsibleCard/src/components/Group/Group.styles.js
packages/CollapsibleCard/src/components/Header/Header.styles.js
packages/CollapsibleCard/src/components/HeaderLayout/components/Metadata/Metadata.styles.js
packages/CollapsibleCard/src/helper.styles.js
packages/CollapsibleCard/stories/examples/Group.js
packages/CollapsibleCard/stories/examples/HeaderLayout.js
yarn.lock

Implement feedback from QA
- fix border-radius
- fix stories
- slight change to edit mode hover style
http://storybooks.highbond-s3.com/paprika/uxd-851--collapsible-card-qa-feedback

Uxd 851  collapsible card qa feedback

---

.changeset/sharp-trees-cover.md
.semaphore/pre-release.yml
.semaphore/release.yml

- Fixed parsing errors in yml file
- added first changeset commit for https://github.com/acl-services/paprika/pull/962

docs(Panel): UXD-908 use changeset

---

.changeset/pre.json
packages/seducer/package.json

Seducer has been published already, but the version in package.json is not updated, maybe an issue with lerna.
https://www.npmjs.com/package/@paprika/seducer

chore(seducer): UXD-908 fix version

---

.changeset/cool-seas-return.md
.changeset/smooth-cats-battle.md
packages/Tabs/src/Tabs.js
packages/Tabs/src/index.d.ts

- modify proptype and generate .d.ts file

UXD-1019 chore(Tabs): fix typesript issue with defaultIndex prop

---

packages/TextEditor/src/TextEditor.js
packages/TextEditor/src/config/advanced.config.js
packages/TextEditor/src/config/simple.config.js
packages/TextEditor/stories/examples/controlled.js
packages/TextEditor/stories/examples/extendingInit.js
packages/TextEditor/stories/examples/isDisabled.js
packages/TextEditor/stories/examples/uncontrolled.js
packages/TextEditor/stories/examples/useKindEditor.js

add support for rendering advance mode:
http://storybooks.highbond-s3.com/paprika/UXD-1031-Render-Advance-Option

feature(TextEditor): UXD-1031 support for advance editor

---

.changeset/smart-boats-ring.md
packages/ActionBar/src/hooks/useSort/index.js
packages/ActionBar/src/hooks/useSort/useSort.js
packages/ActionBar/src/index.js

Export the data sorting function. Assessment doesn't need to use the component or hooks, just needs the pure function.

feat(ActionBar): UXD-1073 export sortData function

---

.changeset/tiny-cameras-deny.md
packages/ActionBar/package.json

clean up unused action bar dependencies

Uxd 1071 clean up action bar dependencies

---

.changeset/ninety-turtles-brush.md
.changeset/yellow-trains-bake.md
packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.js
packages/DataHeader/src/DataHeader.styles.js

- Data header css fix
- Action bar columns arrangement trigger removal 

Uxd 1091 UI fix round 2

---

.changeset/chilled-meals-joke.md
packages/DataGrid/src/hooks/useGridEventHandler.js

Uxd 1091 fix data grid

---

packages/InlineEditors/stories/examples/Table.js

small improvement to inline-editor example
http://storybooks.highbond-s3.com/paprika/XD-1130-adding-inline-editor-example

feature(Table): UXD-1130 improving inline editor example

---

.changeset/little-planes-thank.md

chore(L10n): ISSUE-XXX Bump version

---

.changeset/many-coats-think.md
packages/CollapsibleCard/src/components/Header/Header.styles.js

https://aclgrc.atlassian.net/browse/UXD-1095
Old:
New:
Old edit:
New edit:
New group still works:

style(CollapsibleCard): UXD-1095 Improve hover styles

---

.changeset/good-moles-swim.md

docs(Pill): UXD-1281 Deprecate the pill on npmjs.org

---

.changeset/young-comics-warn.md
packages/seducer/src/getTypes.js

Fix issue noted on [GRCPRD-5023](https://aclgrc.atlassian.net/browse/GRCPRD-4980) and use key instead of fn.name to avoid minification issues that turn calls to action.type resulting in undefined values.
This solves for minified code to not throw [this error](https://github.com/acl-services/paprika/blob/cee049b906846928d54e6cace0875f62591704d5/packages/seducer/src/reducer.js#L48)
When defining the actions for the reducer [here](https://github.com/acl-services/paprika/blob/%40paprika/inline-editors%400.2.0-next.0/packages/InlineEditors/src/Table/store.js#L11), we noted that a minification process will change the code can produce objects with minified names. In this [babel try console](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=M …

fix(seducer): use key instead of fn name to avoid minification issues

---

.changeset/yellow-waves-worry.md
packages/Calendar/src/index.js

There's no file called `tokens` in this package, so just delete it

fix(Calendar): UXD-1371 fix calendar build

---

.changeset/chatty-hornets-report.md
.changeset/sweet-toys-kneel.md
packages/ActionBar/src/hooks/useSort/useSort.js

Whoops
https://youtu.be/lbVdyPZiOLM

fix(ActionBar): PDTVT-1584 Invoke the function

---

.changeset/warm-moles-roll.md
packages/OverflowMenu/src/OverflowMenu.js

fix(OverflowMenu): UXD-1399 fix a11y

---

.changeset/early-rockets-push.md
packages/ListBox/src/hooks/hooks.js

Don't try to focus `trigger` if there's no ref.
https://aclgrc.atlassian.net/browse/UXD-1664

UXD-1664 Don't try to focus trigger if there's no ref 🐐

---

.changeset/sixty-olives-happen.md
packages/Tokens/src/tokens.yaml

Uxd 1770 fix background base

---

scripts/pestle/mainCLI.js

avoid unnecessary story file creation attempts

chore(Pestle): UXD-1584 check if story exists

---

packages/DataTable/package.json
packages/DataTable/src/DataTable.styles.ts
packages/DataTable/src/DataTable.tsx
packages/DataTable/src/components/InfiniteLoader/InfiniteLoader.tsx
packages/DataTable/src/components/TableBody/TableBody.styles.ts
packages/DataTable/src/components/TableBody/TableBody.tsx
packages/DataTable/src/components/TableHeader/TableHeader.styles.ts
packages/DataTable/src/components/TableHeader/TableHeader.tsx
packages/DataTable/src/components/TableRow/TableRow.styles.ts
packages/DataTable/src/components/TableRow/TableRow.tsx
packages/DataTable/src/components/ThemeContext/ThemeContext.tsx
packages/DataTable/src/components/ThemeContext/index.ts
packages/DataTable/src/helpers/rowHeightHelper.ts
packages/DataTable/src/shared.styles.ts
packages/DataTable/src/types.ts
packages/DataTable/stories/examples/Performance.tsx
packages/DataTable/stories/examples/Showcase.tsx
yarn.lock

Still WIP, there're more details than I thought 😅  but honestly if this PR can be merged first (to avoid merging conflicts) I'll do the following things in the next PR:
demo should be on http://storybooks.highbond-s3.com/paprika/UXD-1832-refactor-styles soon

Uxd 1832 refactor styles

---

packages/DataTable/src/DataTable.tsx
packages/DataTable/src/components/TableHeader/TableHeader.styles.ts
packages/DataTable/src/hooks/useSticky.ts
packages/DataTable/stories/examples/Showcase.tsx

Implementing sticky columns. Support `isSticky` configuration on the `columns` prop
http://storybooks.highbond-s3.com/paprika/UXD-1795-sticky-columns/?path=/story/table-datatable--showcase

UXD-1795 sticky columns

---

packages/DataTable/index.d.ts
packages/DataTable/src/DataTable.styles.ts
packages/DataTable/src/DataTable.tsx
packages/DataTable/src/components/InfiniteLoader/InfiniteLoader.tsx
packages/DataTable/src/components/InfiniteLoader/useItemSizeCalculator.tsx
packages/DataTable/src/components/TableRow/TableRow.tsx
packages/DataTable/src/components/react-table-config.d.ts
packages/DataTable/stories/DataTable.stories.ts
packages/DataTable/stories/examples/Kitchensink.tsx
packages/DataTable/stories/examples/Showcase.tsx

https://aclgrc.atlassian.net/browse/UXD-1836

UXD-1836 Make infinite loader optional; add more examples

---

.changeset/red-beers-arrive.md

Bump the version of the `<L10n>` component and trigger a version bump by `lerna` for all dependent packages.
https://aclgrc.atlassian.net/browse/L10N-1139

L10N-1139 add changeset to bump dependent packages of L10n 🐐

---

.changeset/witty-tables-talk.md
packages/DataTable/README.md
packages/DataTable/src/DataTable.tsx
packages/DataTable/src/components/InfiniteLoader/InfiniteLoader.tsx

fix(DataTable): fix infinite loader rendering

---

.changeset/sweet-lions-laugh.md
packages/Tag/package.json
packages/Tag/src/Tag.js
packages/Tag/src/Tag.styles.js
packages/Tag/stories/Examples/Variations.js
yarn.lock

https://aclgrc.atlassian.net/browse/UXD-1707
Tag Icon closing Icon (X icon) background color needs to be changed depends on the tag background.
ex)
If the background of the tag is considered as “light” (e.g. light grey) then the icon will be Grey lighten 30 #8A8A8A
If the background of the tag is considered as “dark” (e.g. black) then the icon will be Grey lighten 70 #F0F0F0
details of code change / secondary purposes of this PR
Icon “times circle” 20px to remove the tag.
- Light background: Grey lighten 30 #8A8A8A
- Dark background: Grey lighten 70 #F0F0F0
- Medium tag with icon paddings: [icon] 4px [label]
- indicate if changes were …

Uxd 1786 update tag

---

.changeset/seven-hounds-check.md
packages/ResizeDetector/README.md
packages/ResizeDetector/src/ResizeDetector.tsx

Made ResizeDetector props optional
https://github.com/acl-services/paprika/pull/1197

UXD-1888 Fix: made ResizeDetector props optional

---

.changeset/bright-dingos-train.md

@paprika/external-link is deprecated and deleted from this repo. Changeset cannot find it

fix(Paprika): fix release

---

.changeset/afraid-feet-unite.md
packages/ResizeDetector/src/ResizeDetector.styles.ts

Change `ResizeDetector` from `span` to `div`
https://aclgrc.atlassian.net/browse/UXD-1888

UXD-1888 change span to div

---

.changeset/gorgeous-ways-cover.md
packages/Filter/src/hooks/defaultReducer.js
packages/Filter/src/hooks/useFilter.js

The state couldn't keep track of the updated data earlier, so we added a helper so user can manually refresh the state. 
to use the updateData hook, we can use `useEffect` in the app and monitor if the data has been updated. (Credits to Yushan and Andrei for the advice 🙏)
http://storybooks.highbond-s3.com/paprika/ASM-1812--filter-update-data
https://aclgrc.atlassian.net/browse/ASM-1812

feat(Filter): ASM-1812 added updateData hook

---

.changeset/grumpy-beds-explain.md
packages/Spinner/package.json
packages/Spinner/src/Spinner.js
packages/Spinner/src/Spinner.styles.js
packages/Spinner/stories/Spinner.backyard.stories.js
packages/Spinner/stories/Spinner.stories.js
packages/Spinner/stories/examples/Showcase.js

Remove all the className and replace it with styled component + update the storybook by using CSF
http://storybooks.highbond-s3.com/paprika/UXD-1574-spinner-collapsible-styling-update-documentation
commended_

UXD-1633 Spinner styling update documentation

---

.changeset/red-squids-rhyme.md
packages/Panel/src/components/Footer/Footer.styles.js
packages/Tokens/src/tokens.yaml

[_clear, one sentence description of primary purpose of this PR_](https://aclgrc.atlassian.net/wiki/spaces/UX/pages/2403795120/Panels+QA)
change panel and modal footer hexcode to #f0f0f0

UXD-1959 Footer background color update

---

packages/DataTable/src/hooks/useBestTableDimensions.ts

fix(DataTable): UXD-2004 rerender scroll bar fix

---

.changeset/many-buses-own.md
packages/FormElement/README.md
packages/FormElement/src/components/Help/Help.js
packages/FormElement/src/components/Label/Label.js
packages/FormElement/stories/examples/Everything.js
packages/FormElement/stories/examples/Showcase.js

Add Tooltip alignment as a prop. Also set the default to Top
https://aclgrc.atlassian.net/browse/SNP-2547
http://storybooks.highbond-s3.com/paprika/SNP-2535-update-tool-tips-in-form

SNP-2547 Enable tooltip alignment as a prop

---

.changeset/early-shrimps-unite.md
.changeset/smart-bugs-reflect.md
.changeset/spotty-cherries-love.md
.changeset/tiny-dingos-hammer.md
packages/Modal/package.json
packages/Modal/src/components/Header/Header.js
packages/Overlay/package.json
packages/Panel/package.json
packages/Panel/src/components/Header/Header.js
packages/Panel/stories/Panel.backyard.stories.js
packages/Panel/stories/sandbox/WebComponent.js
packages/Takeover/package.json
yarn.lock

Fix an issue with the focus locking being too greedy in the `<Panel>` when it is wrapped in a web component.
- The issue was reported and addressed in a recent update of the underlying `react-focus-lock` library used:
https://github.com/theKashey/react-focus-lock/issues/188
- Updated the `<Overlay>` (used by the `<Panel>`) as well as the `<Modal>` and `<Takeover>`.
- The update introduced a new bug however: the close button in the header would be excluded from the tab sequence if it was implemented as a `<Button.Close isSemantic={false}>` (ie `<span role="button" tabindex="0">`).  To compensate, the default value for the `isSemantic` prop in the headers of all these components is now `true` (with an `isCloseButtonSemantic` prop added to the `<Panel.Header>` and `<Modal.Header>` in case …

RNG-372  Fix focus lock for web components 🐐

---

.changeset/famous-bulldogs-sip.md
.changeset/sour-boats-suffer.md
packages/Filter/src/Filter.js
packages/Filter/src/Filter.styles.js
packages/Panel/src/components/Dialog/Dialog.js
packages/Stylers/src/helpers.scss
packages/Stylers/src/includes.js

Add missing padding back to filter panel to match the panel style
ticket: https://aclgrc.atlassian.net/browse/UXD-2066
http://storybooks.highbond-s3.com/paprika/UXD-2066-missing-padding-on-filter-panel

fix(Filter): UXD-2067 Filter panel miss padding

---

packages/Takeover/src/components/Footer/Footer.js
packages/Takeover/stories/TakeoverStory.js

update  footer button to large in storybook
http://storybooks.highbond-s3.com/paprika/UXD-1980 set large button

fix(takeover): UXD-1980 set large button

---

.changeset/sharp-panthers-thank.md
packages/ListBox/src/components/Filter/helpers.js

Display divider when there are results below.
(Also prevent filter from matching with divider)
Add another filter to filter out the dividers that do not have any options folowing
http://storybooks.highbond-s3.com/paprika/VRMRG-1553--display-list-box-divider
Before:
After:
https://aclgrc.atlassian.net/browse/VRMRG-1553

fix(ListBox): VRMRG-1553 Display divider when there are results

---

packages/DataTable/stories/DataTable.mdx
packages/DataTable/stories/DataTable.stories.ts
packages/DataTable/stories/examples/UsingCalc.tsx

https://aclgrc.atlassian.net/browse/UXD-2130
Adding docs for how to use `maxHeight` and `maxWidth`, see http://storybooks.highbond-s3.com/paprika/UXD-2130-data-table-docs/?path=/story/table-datatable-docs--page#table-height-and-width-calculation

docs(DataTable): UXD-2130 add docs for maxHeight maxWidth props

---

.changeset/nasty-chicken-destroy.md
packages/Modal/src/components/FocusLock/FocusLock.js
packages/Modal/stories/Modal.backyard.stories.js
packages/Overlay/src/Overlay.js
packages/Panel/stories/Panel.backyard.stories.js
packages/Panel/stories/sandbox/WithPendoPopover.js
packages/Panel/tests/Panel.cypress.js
packages/Takeover/src/components/FocusLock/FocusLock.js
packages/Takeover/stories/Takeover.backyard.stories.js
packages/helpers/src/focusLockWhiteList.js
packages/helpers/src/index.js

https://aclgrc.atlassian.net/browse/UXD-2124
- added `pendo-designer-container` into the whitelist
- extract the whitelist function into helper package
- added storybook examples
- added a cypress test to test this whitelist function
can be tested here  http://storybooks.highbond-s3.com/paprika/UXD-2124-add-whitelist/?path=/story/messaging-panel-backyard-sandbox--with-pendo-popover-story
http://storybooks.highbond-s3.com/paprika/UXD-2124-add-whitelist …

UXD-2124 add item in to pendo whitelist

---

packages/ListBoxBrowser/stories/ListBoxBrowser.multiple.stories.js
packages/ListBoxBrowser/stories/examples/Lazy.js

This is related to https://aclgrc.atlassian.net/browse/RAPRM-3498
This story wasnt loading before:
http://storybooks.highbond-s3.com/paprika/fix-storybook-listboxbrowser

RAPRM-3772 - Fix storybook story of ListBoxBrowser

---

.changeset/breezy-steaks-taste.md
packages/Takeover/src/Takeover.js

fix(takeover): FIX-takeover fix wrong proptype

---

packages/DataTable/tests/DataTable.cypress.js

test(DataTable): XX-fix fix spec

---

.semaphore/paprika-status-a11y.yml
.semaphore/paprika-status.yml
.semaphore/pre-release.yml
.semaphore/release.yml
.semaphore/semaphore.yml

chore(all):   fix sempahore build

---

.changeset/fast-tips-remember.md

Adds a `changeset` that was forgotten in https://github.com/acl-services/paprika/pull/1309 to trigger the release of a new version.
https://diligentbrands.atlassian.net/browse/FS-4709

FS-4709 Add changeset for recent update to FormElement

---

.changeset/ten-rivers-pay.md
packages/L10n/src/locales/index.js

Add a changeset to release latest L10N updates
Add a changeset to release latest L10N updates since previous PR did not https://github.com/acl-services/paprika/pull/1317 

fix(l10n): ADM-5382 adds new locale support by releasing them with a changeset
