packages/Button/readme.md
packages/Button/src/Button.js
packages/Button/src/CloseButton.js
packages/Button/src/IconButton.js
packages/RawButton/readme.md
packages/RawButton/src/RawButton.js

Add prop descriptions and `readme.md` files for both the `<RawButton>` and `<Button>`.
- Also removed unneeded `className` prop from `<RawButton>`.

UX-467 Add some basic documentation for RawButton and Button 🐐

---

packages/RawButton/test/RawButton.spec.js

Add `react-testing-library` "unit" tests for `<RawButton>`.
✓ Renders with default props
✓ Renders with custom props
✓ Fires onClick callback when clicked
✓ Fires onClick callback when keypressed
✓ Does not fire onClick callback when disabled
✓ Propagates click events by default
✓ Does not propagate click events when canPropagate=false
✓ Is focussable via ref
✓ Is focussable via callback ref

UX-437 Add react-testing-library tests for RawButton 🐐

---

packages/Button/test/Button.spec.js
packages/RawButton/test/RawButton.spec.js

Add `react-testing-library` "unit" tests for `<Button>`.
- Very similar approach to tests for `<RawButton>` (https://github.com/acl-services/paprika/pull/73)
- Adjusted `<RawButton>` tests to better cover `isDisabled` scenario.
✓ Renders with default props
✓ Renders a span when isSemantic=false
✓ Renders with custom props
✓ Fires onClick callback when clicked
✓ Does not fire onClick callback when disabled
✓ Propagates click events by default
✓ Does not propagate click events when canPropagate=false
✓ Is focussable via ref
✓ Is focussable via callback ref

UX-437 Add react-testing-library tests for Button 🐐

---

packages/Button/src/CloseButton.styles.js
packages/Button/src/IconButton.js
packages/Button/src/IconButton.styles.js

Resolve styling regression with `<Button.Icon>` and `<Button.Close>`.
- Refactored some `.styles.js` files to use the styled-components `css` helper, to contribute to https://github.com/acl-services/paprika/issues/98
Screener regression that was fixed:

UX-346 Fix Button styling 🐐

---

packages/Tokens/package.json

- babel-runtime should be a dependency, not a dev dependency.
---
---
---

Fix dev depencies babel runtime

---

packages/CollapsibleChecklists/src/components/Group/Group.js

As per AC, when click on a Group's checkbox, it should expand to reveal the children.
It will also select the children (but it already does that).
After expanding it will also fire`props.onExpand()`.
Note that if `onExpand` makes an API call to update the Group's children, the children will NOT get selected. The consumer will need to click on the checkbox again after the API has completed to select them.
This illustrates what happens when

PD-12487 Expand children when select group

---

packages/DropdownMenu/package.json
packages/DropdownMenu/src/DropdownMenu.js
packages/DropdownMenu/src/components/Confirmation/Confirmation.js
packages/DropdownMenu/stories/cypress.stories.js
packages/DropdownMenu/stories/examples/DropdownMenuExample.js
packages/DropdownMenu/test/dropdownMenu.cypress.js
packages/DropdownMenu/test/dropdownMenu.spec.js

Ensure tabbing into trigger button only takes one tab action
Convert failing spec tests (because of above change) to cypress test
Ensure confirmation panel buttons render as <spans> so that consuming application styles doesn't override them.
This is a minor bugfix on the component - Please bump to `0.1.2`
Before
After

Dropdown tweaks, Tab focus, Buttons as spans, create Cypress test

---

packages/FormElement/src/components/Help/Help.js

- we want to propogate the zindex to also the tip, so when someone passes in
`<Popover.Help zIndex={100} />`
- it will work properly for both the tip and the popover content
---
---
---

PD-12723 propagate zindex to tip

---

packages/CollapsibleChecklists/stories/examples/Advanced.js

Really its still v0.2.0 as the component didnt change.
There was a bug in the story that made the component act funky:
if you expand 'Football' that retrieves from an API call (1 is selected, 1 is not).
then change them to both be selected
then collapse 'Football'
then expand 'Football'
it would retrieve 'Football' from the API again, and make 1 selected and 1 not.
This is just a change in the story.  Comonent is unchanged.  It is up to the consumer to decide what to do when they expand (e.g. if the code should run every time, or just the first time).

PD-12487 Fix bug in story

---

scripts/storybookLink.js

This should fix the problem when the issue name is not the branch name. This will always add the storybook link at the bottom of this description. 
---
---
---
<a href='http://storybooks.highbond-s3.com/paprika/UX-499-storybook-link-patch' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/UX-499-storybook-link-patch</a>

fixing searching issue by branch name

---

packages/CollapsibleText/src/CollapsibleText.js

Semantic `<buttons>` are great – in a perfect world.  In the real world, global CSS is a nightmare that shatters our dreams.
Ew.

UX-570 Add isSemantic={false} to CollapsibleText Button 🐐

---

packages/DatePicker/src/components/Calendar/Calendar.js
packages/DatePicker/src/components/ShortcutPanel/ShortcutPanel.js
packages/DatePicker/src/components/ShortcutPanel/ShortcutPanel.styles.js

Use the Paprika dropdown in a module that also uses acl-ui 3 buttons. Eg in results questionnaires.
Some styles are being overridden by acl-ui 3 styles.
Fixes include
Ensure Paprika buttons are non-semantic
Ensure component has a background colour
Ensure label is displaying correct styles for flex layout
Before:
---
<a href='http://storybooks.highbond-s3.com/paprika/ux-586-datepicker-prevent-aclui-style-overrides' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/ux-586-datepicker-prevent-aclui-style-overrides</a>

ux-586-datepicker-prevent acl-ui3 style overrides

---

packages/DatePicker/src/DatePicker.js

Previously date picker input was being reset if date object is null.
---
---
<a href='http://storybooks.highbond-s3.com/paprika/XD-5802-date-picker-no-date-bug' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/XD-5802-date-picker-no-date-bug</a>

XD-5802-Ensure input works even with no date provided

---

packages/DatePicker/src/DatePicker.js
packages/DatePicker/src/components/DateInput/DateInput.js
packages/DatePicker/stories/DatePicker.stories.js
packages/DatePicker/test/DatePicker.spec.js

Allow the consuming application to know an invalid date string has been parsed in the component so that it can react accordingly displaying error messages if required. (Needed in results)
@nahumzs minor version bump required
---
---
<a href='http://storybooks.highbond-s3.com/paprika/XD-5802-add-date-picker-parse-error' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/XD-5802-add-date-picker-parse-error</a>

XD-5802-Adding onError prop to DatePicker

---

packages/DatePicker/src/DatePicker.js

Prevent flicker of Datepicker calendar on close.
Giphy captures below not showing flicker very well, better to run locally in storybook to see change
---
Context action (closing calendar)
<a href='http://storybooks.highbond-s3.com/paprika/xd-5802-datepicker-prevent-flicker' target="_blank" rel="noopener">http://storybooks.highbond-s3.com/paprika/xd-5802-datepicker-prevent-flicker</a>

XD-5802-Prevent DatePicker calendar flicker on close

---

packages/DropdownMenu/test/dropdownMenu.cypress.js
packages/ListBox/test/helpers/selectors.js
packages/ListBox/test/specs/multi/ListBox.multi.spec.js
packages/ListBox/test/specs/single/ListBox.single.spec.js
packages/Popover/src/Popover.js
packages/Popover/src/components/Card/Card.js
packages/Popover/src/components/Content/Content.js
packages/Popover/src/components/Tip/Tip.js
packages/Popover/src/components/Tip/Tip.styles.js
packages/Popover/src/components/Trigger/Trigger.js
packages/Popover/tests/helpers/selectors.js

Don't let the `<Tip>` fire point events (`onMouseOver`, `onMouseOut`, `focus`) which will close the "tooltip" (`isEager`) version.
- Also added some `data-pka-anchor` attributes throughout `<Popover>`.
- **💥 [BREAKING CHANGE]:** Adjusted `data-pka-anchor` values to use a `.` delimiter instead of a `-`, for consistency (ex `popover-trigger` → `popover.trigger`)

UX-480 Popover tooltip fixes 🐐

---

packages/SidePanel/src/components/Overlay/Overlay.styles.js

- zindex was missed in overlay styles
---
---
---

PD-13509 add zindex for overlay

---

packages/SidePanel/src/components/Group/Group.js
packages/SidePanel/src/components/Group/Group.styles.js
packages/SidePanel/stories/SidePanel.Group.stories.js

---
---
- Make it so that the Group and Overlay component has the same z-index
- Make it so that the Overlay is clickable even if the Group has a width of 100%
---

PD-13509 fix side panel overlay with percentage width

---

packages/CollapsibleChecklists/src/components/Item/Item.js

Make CollapsibleChecklists.Item accept more props, to pass to the input (i.e. a `ref`).

PD-13298 Support more props in CollapsibleCheckLists.Item

---

packages/Tokens/src/tokens.yaml

---
- The token rename, is because added / selected / removed doesn't make sense in citation mode. We should make it a bit more generic and most simple way is just to use the colour.
- Modified one token from lighten -> darken
---
---

Pd 13695 fix token colour

---

packages/SidePanel/src/components/LockBodyScroll.js

- Resolves https://github.com/acl-services/paprika/issues/277
- make lock body scroll overflow hidden !important to fight with inline css conflicts
---
---
- there is some inline css overflow auto in projects... that conflicts with this, so need to make it !important
---

PD-13719 make overflow hidden important

---

packages/Sortable/package.json
packages/Sortable/src/Sortable.js
packages/Sortable/src/components/SortableItem/SortableItem.js
packages/Sortable/tests/Sortable.cypress.js
yarn.lock

MINOR (backward compatible) change to SortableItem
Using the paprika/sortable i was getting this axe error:
`Ensure ARIA attributes are allowed for an element's role.`
Digging into it, it seems to be because the `<li>` elements have an `aria-roledescription` (added both by us, and by the react-beautiful-dnd library) and I need to remove those.
I updated to the latest version of the react-beautiful-dnd library, as they no longer add that attribute. I also removed where we add the attribute. Now the axe error is gone, yay.
But when using screen reader in Chrome, it no longer says “Draggable Item. Press space to lift”.
No announcement is made in Chrome (though one is made in Safari) even though the sortable item has `aria-labelledby="rbd-lift-instruction-0"` and the page includes:
```<div …
```

PD-13299 Fix Axe error on SortableItem

---

packages/Popover/src/Popover.js
packages/Popover/src/components/Content/Content.js
packages/Popover/stories/Popover.stories.js
packages/Popover/stories/examples/Basic.js
packages/Popover/stories/examples/Controlled.js
packages/Popover/stories/examples/FocusTest.js

Bug fix in the Popover component.
Before this PR, when you open the popover, focus goes into it.  Then when you tab through its content, focus goes to the address bar (since the Popover is added to the bottom of the DOM).
After this PR, when you open the popover, focus goes into it. Then when you tab through its content, focus goes to the next item on screen and the popover closes.
This is maybe premature and it needs to be tested with `isEager` and some other props.... just want to get some feedback.
Notice the `tabIndex` before (3), how it is removed (-1), then how it is restored (3).
Notice I can tab right through the popover, in both directions.

Pd 13298 popover focus

---

packages/Input/README.md
packages/Input/src/Input.js
packages/Input/stories/Input.stories.js
packages/Input/stories/examples/Uncontrolled.js

Make the `Input` support being used as an uncontrolled component.
http://storybooks.highbond-s3.com/paprika/pd-13809-uncontrolled-input

PD-13809 Support being uncontrolled

---

packages/DatePicker/README.md
packages/DatePicker/src/DatePicker.js
packages/DatePicker/src/components/DateInput/DateInput.js
packages/DatePicker/stories/DatePicker.stories.js
packages/DatePicker/test/DatePicker.spec.js

Date Picker doesn't currently includes the `hasError` prop on the DatePicker input component. When the Date Picker component is used as as child of the Form Element component the `DatePicker.Input` is not an immediate child and so the `hasError` prop is not added to the input therefore not highlighting the input as red when `FormElement` has an error.
Side changes
- Expanded DatePicker readme to include props
- Retained `hasError` prop on the `DatePicker.Input` to avoid breaking change
http://storybooks.highbond-s3.com/paprika/ux-681-datepicker-has-error-in-formelement-fix
Before
After

Ux 681 datepicker has error in formelement fix

---

.semaphore/semaphore.yml
screener.config.js

Use a Semaphore secret to protect the Screener API Key.
- Also trying to add the `branch` config to `screener.config.js` for better Screener experience (grouping builds by branch name). This may need to be reverted if it still won't recognize the `baseBranch`.
- Also fixed the `includeRules` for the Button story.
https://aclgrc.atlassian.net/browse/UX-695

UX-695 Use secret SCREENER_API_KEY 🐐

---

packages/ListBox/src/components/Divider/Divider.styles.js

- make divider left aligned instead of centered
http://storybooks.highbond-s3.com/paprika/PD-14060-listbox-divider

PD-14060 make divider left aligned

---

packages/Checkbox/CHANGELOG.md
packages/Checkbox/src/Checkbox.js
packages/Checkbox/stories/examples/CheckboxAlign.js
packages/Checkbox/stories/examples/CheckboxGrouping.js
packages/Checkbox/stories/examples/Showcase.js
packages/Checkbox/tests/Checkbox.spec.js

- fix checkboxStates import, before `import Checkbox, { checkedStates } from '@paprika/checkbox' was not working
- Changed it so it is similar to `Button.Kinds`. So now we use `Checkbox.States` instead of exporting `checkboxStates`
http://storybooks.highbond-s3.com/paprika/PD-13960-fix-checkboxstates

PD-13960 fix checkbox states

---

packages/Popover/CHANGELOG.md
packages/Popover/src/Popover.js
packages/Popover/src/components/Content/Content.js
packages/Popover/src/components/Tip/Tip.js
packages/Popover/stories/examples/Basic.js

- add `isPortal` prop that allows consumer to render popover inline with the DOM or as a portal
http://storybooks.highbond-s3.com/paprika/PD-14210-add-isportal-prop

PD-14210 add isPortal prop to popover

---

packages/Popover/src/components/Trigger/Trigger.js
packages/Popover/stories/examples/WithTriggers.js

Adding `isOpen` to `<Popover.Trigger />` render child function params to show different trigger status. This will be used in table navigation
http://storybooks.highbond-s3.com/paprika/UX-633-passing-isOpen-into-popover-trigger

UX-633 Adding isOpen to popover trigger render function params

---

.semaphore/semaphore.yml
package.json

Enable GitHub integration with Screener for Semaphore 2.0 builds.
- Inspired by workaround by @danwu: https://github.com/acl-services/visualizer/pull/2823
- Native Semaphore 2.0 support in `screener-storybook` is waiting on: https://github.com/screener-io/screener-runner/pull/80
Specifically, these lines: https://github.com/screener-io/screener-runner/blob/ca976779a22c940f0af0707f0e6959546d04b0ee/src/ci.js#L79-L81
https://aclgrc.atlassian.net/browse/STAR-128
https://screener.io/v2/dashboard/H1OkdIZtV.acl-services-paprika/STAR-128--reintegrate-screener

STAR-128 Integrate Screener with GitHub 🐐

---

packages/Button/src/Button.js
packages/Button/stories/examples/Basic.js
packages/Button/test/Button.spec.js
packages/Checkbox/src/Checkbox.js
packages/Checkbox/stories/examples/CheckboxGrouping.js
packages/Radio/src/Radio.js
packages/RawButton/src/RawButton.js
packages/RawButton/stories/examples/Basic.js

Allow disabled `<Buttons>` (with `isSemantic={false}`) to be tabbable if `tabIndex` prop is supplied.
- Turns out a native `<button>` with a `disabled` attribute cannot be focussed, even with `tabindex=0`.  So this approach will only work with `isSemantic={false}` `<Buttons>`.
- Also applied same code to `<RawButton>`.
- Also applied a symmetrical coding approach to `<Checkbox>` and `<Radio>`.
- Added a demonstration of `tabindex` propagation to Checkbox Group story in Storybook.
http://storybooks.highbond-s3.com/paprika/STAR-136--button-tabindex-override
https://aclgrc.atlassian.net/browse/STAR-136
https://aclgrc.atlassian.net/browse/BOT-2067

STAR-136 Allow tabIndex override for Buttons 🐐

---

packages/Pill/src/Pill.js
packages/Pill/src/Pill.styles.js
packages/Pill/stories/examples/SizesColors.js

- add light orange, light blue pill color to pill
http://storybooks.highbond-s3.com/paprika/PD-14384-fix-pill-color

PD-14384 add light orange and light blue for pill

---

packages/Button/src/Button.js
packages/Button/src/LinkButton.js
packages/Button/stories/examples/Basic.js
packages/RawButton/stories/examples/Basic.js

`<Button.Link />` doesn't render any extra props on the element, and missing `a11yText`
http://storybooks.highbond-s3.com/paprika/PD-14427-Fix-Button.Link

PD-14427 Fix Button.Link props

---

packages/Checkbox/src/Checkbox.js
packages/Checkbox/src/Checkbox.styles.js
packages/Checkbox/stories/examples/CheckboxGrouping.js
packages/Heading/src/Heading.js
packages/Heading/src/Heading.styles.js
packages/Radio/src/Radio.js
packages/Radio/src/Radio.styles.js

Styling adjustments for `<Checkbox>`, `<Radio>`, + `<Heading>`.
- Inline comments to justify changes.
http://storybooks.highbond-s3.com/paprika/UX-702--styling-adjustments-checkbox-radio-heading
https://aclgrc.atlassian.net/browse/UX-702

UX-702  Styling adjustments for Checkbox, Radio, + Heading 🐐

---

packages/L10n/build-translations.js
packages/ListBox/src/components/Content/Content.js
packages/ListBox/src/components/Filter/Filter.js
packages/ListBox/stories/Filter.stories.js

This fixed #472 where the filter was not resetting properly when a onBlur were happening, also fix an issue where using a tab on the trigger was not closing the popover. 
http://storybooks.highbond-s3.com/paprika/STAR-188-Listbox-issue-472

Star 188 listbox issue 472

---

packages/ListBox/src/hooks/hooks.js
packages/ListBox/src/store/Provider.js
packages/ListBox/src/store/reducer.js

This one improves the behaviour of the scrolling for the ListBox, before the single select was scrolling to the current select option all the time creating a "weird" sensation when using the arrows
http://storybooks.highbond-s3.com/paprika/STAR-188-Listbox-scroll-improvements

Star 188 listbox scroll improvements

---

packages/Confirmation/src/Confirmation.js
packages/DropdownMenu/src/components/Item/Item.js
packages/DropdownMenu/src/components/LinkItem/LinkItem.js

Don't let click events that occur on the buttons inside the `<DropdownMenu.Item>` + `<Confirmation>` propagate – this has undesired consequences when those events dismiss the `<Popover>` and the event bubbles up the element that was underneath.
- Added `canPropagate={false}` props to `<Buttons>` and `<RawButton>` in `<Confirmation>` + `<DropdownMenu>`.
http://storybooks.highbond-s3.com/paprika/UX-738--dropdown-confirmation-propagation-cancelation
https://aclgrc.atlassian.net/browse/UX-738

UX-738 DropdownMenu / Confirmation propagation cancellation 🐐

---

packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Content/Content.js
packages/ListBox/src/hooks/hooks.js
packages/ListBox/stories/examples/multi.js

- Fixed an error in `useOnScrolled`, when the options list got refreshed (for example, when using backend search, we need to replace all the previous options), `state.options[state.activeOption]` might be undefined
- Call `onClickCancel` in `Listbox.Content` when it's on blur. When the listbox has a footer, users can either click the cancel button on the footer or click outside to cancel the action

SNP-131 Listbox small fix

---

packages/Icon/CHANGELOG.md
packages/Icon/src/svg/Filter-Alt.svg
packages/Icon/src/svg/Filter.svg

Rename `FilterAlt` icon to `Filter` and update source `svg` with a new version that is not "🔥💩"
- Reference: https://github.com/acl-services/wasabicons/pull/13#issuecomment-621417776
http://storybooks.highbond-s3.com/paprika/STAR-220--filter-icon-update/?path=/story/icon--all-icons
New / renamed version of `Filter` icon
https://aclgrc.atlassian.net/browse/STAR-220

STAR-220 Update Filter icon 🐐

---

packages/ListBox/src/components/Trigger/Trigger.js

In projects, we need to assign unique `data-qa-anchor` on different listbox trigger

SNP-200 Passing more props on listbox trigger

---

packages/Modal/CHANGELOG.md
packages/Modal/src/components/Header/Header.js

Set the modal header close button to semantic false
http://storybooks.highbond-s3.com/paprika/xd-7713-modal-header-close-button-semantic-false

XD-7713 - set modal header isSemantic false

---

packages/Input/CHANGELOG.md
packages/Input/src/Input.js
packages/Input/tests/input.spec.js

Fix bug where empty string as value is causing a warning, set onChange callback to not required
http://storybooks.highbond-s3.com/paprika/ux-614-fix-input-evaluating-value-false
https://aclgrc.atlassian.net/browse/UX-746

Ux 614 fix input evaluating value false

---

.eslintrc
packages/Modal/src/Modal.js
packages/Modal/src/components/Header/Header.js
packages/Popover/src/Popover.js
packages/Popover/src/components/Trigger/Trigger.js

Lint for `sc` to be used as the name of styled components imports. 
I left `Sbook` imports from `"storybook/assets/styles/common.styles"`, LMK if that can be `sc` as well.
http://storybooks.highbond-s3.com/paprika/UX-346-sc-lint

UX-346 lint rule for sc import

---

packages/helpers/CHANGELOG.md
packages/helpers/src/customPropTypes.js

As discussed in https://github.com/acl-services/acl-exception/pull/7657/files#r434794944
This pr is updating the RefOf method helper to support functional components so that we don't get any more invalid prop types warnings when using class components
http://storybooks.highbond-s3.com/paprika/tw-204-ref-proptype-support-functional-components

tw-204 change refOf function to support func components

---

packages/Button/CHANGELOG.md
packages/Button/src/Button.js
packages/Button/src/Button.styles.js
packages/Button/src/CloseButton.styles.js
packages/Button/src/IconButton.styles.js
packages/Button/src/LinkButton.js
packages/Button/stories/Button.stories.js
packages/Button/stories/examples/Variations.js
packages/Toast/src/Toast.styles.js
screener.config.js

Adjust the styling of `<Button.Icon kind='minor' isDisabled>` and the icon in the `<Toast>`.
- Also renamed the `Basic` storybook story to `Variations`, in line with new patterns.
- Also noticed that `<Button.Link isDisabled>` was not actually disabled, so fixed that.
- 💥 Made a small (BREAKING) change to the `<Button.Link>` by renaming `isOpenNewTab` to `shouldOpenNewTab` and changing its default value to `false`.
http://storybooks.highbond-s3.com/paprika/RAPRM-353--button-toast-styling-tweaks
A variety of disabled buttons for exposition / screener testing to Variations story
https://aclgrc.atlassian.net/browse/RAPRM-353

RAPRM-353 Button + Toast styling tweaks 🐐

---

packages/Switch/src/Switch.styles.js

To adjust the sizes of the Paprika Switch component so that it is consistent with the UI Kit.
N/A
http://storybooks.highbond-s3.com/paprika/STAR-255-Switch-component-sizes
Before:
After:
N/A

STAR-255-Switch-component-sizes

---

packages/Overlay/src/Overlay.js
packages/Takeover/src/Takeover.js
packages/Takeover/src/components/Header.js
packages/Takeover/stories/Takeover.stories.js

Implement the propagation of `classNames` for root `<Takeover>` element, as well as `<Takeover.Overlay>` + `<Takeover.Content>`.
- Now propagating all props for Takeover and all Takeover subcomponents via `moreProps`.
- Had to add a `displayName` property to `<Overlay>` for `extractChildren` to work properly.
- Added custom classNames to all subcomponents in the Takeover "Basic" story.
- **BONUS**: avoid errors when the `a11yText` prop is omitted and the children for `Takeover.Header` component is a node by displaying a console.error instead.
http://storybooks.highbond-s3.com/paprika/RAPRM-373--propagate-takeover-props
https://aclgrc.atlassian.net/browse/RAPRM-373

RAPRM-373 Propagate Takeover classnames 🐐

---

.storybook/assets/styles/common.styles.js
.storybook/main.js
.storybook/storyTree.js
packages/Button/src/Button.js
packages/Button/src/Button.styles.js
packages/Button/src/CloseButton.styles.js
packages/Button/src/IconButton.styles.js
packages/Button/src/LinkButton.js
packages/Button/src/LinkButton.styles.js
packages/Button/stories/examples/Variations.js
packages/Calendar/stories/Calendar.stories.js
packages/Calendar/stories/cypress.stories.js
packages/Calendar/stories/screener.stories.js
packages/Calendar/tests/DateRangeCalendar.cypress.js
packages/Calendar/tests/SingleDateCalendar.cypress.js
packages/DataGrid/stories/DataGrid.resize.stories.js

Make sure you can supply a custom colour for the icon in `<Button.Icon kind='minor'>` but without overriding the disabled colour.
- Also refactored the `<Button.Link>` icon styling.
- **BONUS**: Adjusted the Storybook webpack config, as suggested by @alexzherdev.
- **BONUS**: Tidy up of Storybook stories.
http://storybooks.highbond-s3.com/paprika/RAPRM-373--disabled-icon-button-styling/?path=/story/commands-button--variations
https://aclgrc.atlassian.net/browse/RAPRM-373

RAPRM-373 Disabled styling of Button.Icon 🐐

---

packages/Takeover/src/Takeover.js
packages/Toast/package.json
yarn.lock

1. The `<Toast>` had a dependency on an old version of the `@paprika/icon` that didn't include the `ColoredCaution` icon.
2. I mistakenly propagated too many props onto `<Takeover.Content>` that was resulting in multiple classNames being applied in a [previous PR](https://github.com/acl-services/paprika/pull/575).
http://storybooks.highbond-s3.com/paprika/RAPRM-373--fix-toast-and-takeover
https://aclgrc.atlassian.net/browse/RAPRM-373

RAPRM-373 Fix small Toast + Takeover bugs 🐐

---

packages/Radio/CHANGELOG.md
packages/Radio/src/Radio.js

Removing Readonly true on the radio component as this is won't allow input focus in safari.
When used with formElement the radio can now be focused in Safari.
Did some research and I don't believe readonly should ever have been added to this input type and can make it unusable.
http://storybooks.highbond-s3.com/paprika/tw-353-radio-remove-readonly
https://aclgrc.atlassian.net/browse/TW-268
https://aclgrc.atlassian.net/browse/TW-353

Tw 353 radio remove readonly

---

packages/DataGrid/src/DataGrid.js
packages/DataGrid/src/DataGrid.styles.js

After introducing a dynamic scrollbar #566 , a bug was introduced preventing the header to synchronize with the body of the DataGrid, as well as a misaligned between the header and the content when scrolling full to the right side see images.
http://storybooks.highbond-s3.com/paprika/STAR-241-scrolling-horizontal-fix
**before**
**after**

STAR-241 bug(DataGrid) fixing scroll horizontal misaligned  / 🦄.

---

packages/Button/src/Button.js
packages/Button/src/Button.styles.js
packages/Button/stories/examples/Variations.js
packages/ButtonGroup/src/ButtonGroup.js
packages/ButtonGroup/src/components/Item/Item.styles.js
packages/ButtonGroup/stories/examples/Sandbox.js
packages/RawButton/src/RawButton.js
packages/RawButton/src/RawButton.styles.js
packages/RawButton/stories/examples/Basic.js

1. The `<Button>` should not be interpreted as a "toggle button" if the `isActive` prop is not explicitly provided.
2. The `<ButtonGroup>` `focus()` method should focus on the last focused item, not necessarily the _first_ item.
- Also, the styling of various button states has been adjusted to match the intended design (it was a bit off after the introduction of the `whatinput` logic).
http://storybooks.highbond-s3.com/paprika/STAR-258--button-buttongroup-a11y-styling/?path=/story/commands-button--variations
https://aclgrc.atlassian.net/browse/STAR-258

STAR-258 Button + ButtonGroup accessibility + styling 🐐

---

packages/ListBox/src/hooks/hooks.js

Fix list box internal state when options update
`<Listbox > ` watches the change of its children(which is `<Listbox.Option>` ), before we only check if the `value` prop change, we should also check if `isDisabled` `isSelected` is changed to insure the internal state in the provider sync with other places

SNP-233 Fix list box internal state for options update

---

packages/Input/src/Input.js
packages/Input/stories/Input.stories.js
packages/Input/stories/examples/WithCustomClearIconStory.js

- adding an option to pass in a custom icon for the clear button
**Why?**
- in mission control bulk update, clicking the clear button acts as a "reset" action, so we want to use the reset icon here.
http://storybooks.highbond-s3.com/paprika/PDTVT-337-update-input-icon

PDTVT-337 add custom icon for clear

---

packages/RawButton/CHANGELOG.md
packages/RawButton/src/RawButton.js

Currently raw button component doesnt' send event data in onBlur event which can lead to errors working with the popover component
http://storybooks.highbond-s3.com/paprika/uxd-53-fix-raw-button-onblur-pass-event-data
https://aclgrc.atlassian.net/browse/UXD-53

uxd-53 Ensure onblur event data passed in event

---

packages/Button/stories/examples/Variations.js
packages/RawButton/src/RawButton.styles.js

Remove outline on Rawbutton when interaction is with mouse and it receives focus
Before:
After
Visualizer currently makes use of this pattern in the actionButtons component.
http://storybooks.highbond-s3.com/paprika/uxd-59-disable-outline-on-mouse-interaction
https://aclgrc.atlassian.net/browse/UXD-59

uxd-59 remove outline on mouse interaction

---

packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.js
packages/ActionBar/stories/ShowcaseApp/ShowcaseApp.js

- Update Columns Arrangement defaultProps `renderTriggerButton: null`
- To render the raw button trigger by default

PDTVT-293 Update Columns Arrangement defaultProps

---

packages/ActionBar/src/components/Filter/Filter.js
packages/Button/test/Button.spec.js
packages/Confirmation/test/confirmation.spec.js
packages/DateInput/test/DateInput.spec.js
packages/DropdownMenu/test/dropdownMenu.spec.js
packages/ListBox/test/specs/multi/ListBox.multi.spec.js
packages/ListBox/test/specs/single/ListBox.Option.spec.js
packages/ListBox/test/specs/single/ListBox.single.spec.js
packages/Modal/tests/Modal.spec.js
packages/RawButton/test/RawButton.spec.js
packages/Takeover/tests/Takeover.spec.js

Update spec test files with deprecation warnings
Not updated
1. Datepicker `Warning: React does not recognize the clearIcon prop on a DOM element..., spell it as lowercase clearicon instead`
2. DataGrid console output messages
3. DateInput `Warning: value provided is not in a recognized RFC2822 or ISO format.` _Testing string value_
http://storybooks.highbond-s3.com/paprika/UXD-64-update-tests
Issue #611

UXD-64 Update test with deprecation warnings

---

packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.styles.js

Fix ColumnsArrangement overlapping content
Add space between text and switch component `margin-left: ${tokens.spaceSm}`
http://storybooks.highbond-s3.com/paprika/PDTVT-366-columns-arrangement-overlap

PDTVT-366 Fix ColumnsArrangement overlapping content

---

packages/DataGrid/src/components/Cell/Cell.js
packages/ListBox/CHANGELOG.md
packages/ListBox/src/components/Content/Content.js
packages/ListBox/src/components/Trigger/Trigger.js
packages/ListBox/src/helpers/handleKeyboardKeys.js
packages/ListBox/stories/listBox.stories.js
packages/ListBox/test/cypress/ListBox.cypress.js

/ 🦄.
Before this PR  the onkeydown event for `↑`,`↓` , `SPACE`, `ESC` and `ENTER` where under the same function and under onKeyDown event, this creates an interesting behaviour for the Enter key where toggle the listbox opening and closing it when trying it to opening.
The reason why were bound into onKeyDown was because  ↑↓→←  have to have to ability to scroll up and down without lifting the key. 
With this PR this behaviour has been splitted between keydown and keyup, keydown will manage the arrow keys while the keyup will handle Space, Enter and Esc.
This results in a nicer behaviour.   
http://storybooks.highbond-s3.com/paprika/STAR-265-Listbox-on-enter

STAR-265 bug(ListBox) working incorrectly with Enter keydown

---

packages/DataGrid/src/DataGrid.Rows.js

Add title attribute in DataGrid cell header to specify truncated/cut off header label. 
http://storybooks.highbond-s3.com/paprika/UXD-81-datagrid-title-attribute

UXD-81 DataGrid - Add title attribute in cell header

---

packages/Collapsible/src/Collapsible.js

To match current design guidelines for Collapsible. Adjust chevron icon to be an UpArrow when alligned right and expanded and to be a DownArrow when alligned right and collapsed. 
N/A
http://storybooks.highbond-s3.com/paprika/UXD-115-Collapsible-default-chevron
N/A

UXD-115 - Collapsible - Different default Icon depends on position

---

packages/Table/CHANGELOG.md
packages/Table/package.json
packages/Table/src/Table.styles.js

Add default font styling on th elements in Table Component
As discussed - https://github.com/acl-services/acl-exception/pull/7873/files#diff-ea428be058ad84e7b18651badfc2b143R7
No visible changes to the component in storybook as the styles were already coming from other style sources. In a consuming application however that may not be the case
http://storybooks.highbond-s3.com/paprika/UXD-162-Table-th-default-styling
https://aclgrc.atlassian.net/browse/UXD-162

add default font styles on th

---

package.json
packages/Table/CHANGELOG.md
packages/helpers/CHANGELOG.md
scripts/changelogFiles.js
scripts/readmeFiles.js

- Fix bug in changelog script to including an empty CHANGELOG format
- Catch errors in readme script to avoid script failing on dev branch
- Only commit `*.md` files after npm publishing

UXD-164 Fix bug in changelog script and not commit package json

---

packages/Button/src/Button.styles.js

`a` tag elements Hover and visited styles are being set by acl-ui 3. When paprika `Button.Link` components are rendered alongside aclui-3 with kind `secondary` `primary` or 'flat` the hover and visited styles coming from acl-ui 3 are showing (and are dark blue with text underline).
This pr changes those defaults to ensure text that has hover or visited is styled correctly.
http://storybooks.highbond-s3.com/paprika/TW-612-button-default-hover-visited-styles

Tw 612 button default hover visited styles

---

packages/Card/stories/examples/BasicCardContent.js

One of the Card's stories size did not match the desired size based on Figma designs.
- Card had no defined size, therefore it was set to a default value of auto. Added `size={Card.types.size.SMALL}`
http://storybooks.highbond-s3.com/paprikaUXD-224-refactor-styling-Card-fail
https://aclgrc.atlassian.net/browse/UXD-224

UXD-224 Refactor Styling Card Issue

---

packages/Button/CHANGELOG.md
packages/Button/src/LinkButton.js
packages/Button/stories/examples/Variations.js

Allow the `ButtonLink` component (part of the `Button` package) to support an icon. (Required for results design in new collections homepage)
http://storybooks.highbond-s3.com/paprika/tw-612-support-icon-button-link
After
https://aclgrc.atlassian.net/browse/TW-612

Tw 612 support icon button link

---

packages/Button/CHANGELOG.md
packages/Button/src/LinkButton.js

Adding missing `aria-disabled` tag on Buttons `Button.Link` component
https://aclgrc.atlassian.net/browse/TW-612

TW-612 add aria disabled on linkbutton

---

packages/Button/CHANGELOG.md
packages/Button/src/Button.styles.js

Ensure `button.Links` with default button styling are not having their `hover` or `visited` states overridden by common global styles in consuming applications. 
Currently this covers any `a` tag hover, visited styles. 
As required to fix https://aclgrc.atlassian.net/browse/TW-670
http://storybooks.highbond-s3.com/paprika/TW-670-Button-link-default-styling
https://aclgrc.atlassian.net/browse/TW-670

Tw 670 button link default styling resilient to global styles

---

packages/Table/CHANGELOG.md
packages/Table/README.md
packages/Table/src/Table.js

Propagate `<Table.ColumnDefinition>` `moreProps` attributes to the table header (`<th>`) elements.
- `moreProps` were already being propagated to the cell elements (`<td>`), this applies them to the headers too, so that `classNames`, `test-ids`, etc can also be applied to the `th`, which is especially important for an empty table.
- Added a note to the `README` that explains how `<Table.ColumnDefinition>` `moreProps` are handled.
- Did not add to the MDX `Docs` page – the `README` will be added to that page in another upcoming task. 
http://storybooks.highbond-s3.com/paprika/RAPRM-760--table-moreprops
https://aclgrc.atlassian.net/browse/RAPRM-760
This came as a request from @robyn3choi:
> I'm having a problem with `Table` right now, and maybe this is something that's missing in the docs, …

RAPRM-760  Propagate Table.ColumnDefinition moreProps to TH 🐐

---

package.json
yarn.lock

`dompurify` had a critical security alert and is a dependency of `verdaccio`.  `verdaccio` was installed for the initial testing of the paprika release and is no longer needed, so get rid of it (and the security alert).

UXD-389 Remove unused dependency

---

package.json
yarn.lock

Upgrade `screener-storybook`, which will upgrade one of its dependencies (`http-proxy`) which has a high-severity security vulnerability.

UXD-390 Upgrade screener-storybook

---

packages/FormElement/CHANGELOG.md
packages/FormElement/src/FormElement.js
packages/FormElement/src/components/Help/Help.js
packages/FormElement/src/components/Instructions/Instructions.styles.js
packages/FormElement/src/components/Label/Label.styles.js
packages/FormElement/stories/examples/ButtonGroupExample.js
packages/FormElement/stories/examples/CheckboxExample.js
packages/FormElement/stories/examples/NestedExample.js
packages/FormElement/stories/examples/RadioExample.js
packages/Radio/CHANGELOG.md
packages/Radio/src/components/Group/Group.js

Ticket: https://aclgrc.atlassian.net/browse/UXD-451
Addressing the design requirements in https://aclgrc.atlassian.net/browse/UX-797
Changing the spacing around the formElement label so that content is closer by default. If increased spacing is required around the content then it is up to the consumer to add that necessary margin.
These changes will be required in results questionnaires.
Spacing changes include:
FormElement label has smaller bottom margin to content.
Instructions spacing adjusted.
Before:
After:
http://storybooks.highbond-s3.com/paprika/uxd-451-formElement-spacing-tweaks

UXD-451 form element spacing tweaks

---

packages/DropdownMenu/README.md
packages/DropdownMenu/src/DropdownMenu.js
packages/DropdownMenu/src/components/Content/Content.js
packages/DropdownMenu/src/components/Content/index.js
packages/DropdownMenu/src/index.d.ts
packages/DropdownMenu/stories/DropdownMenu.stories.js
packages/DropdownMenu/stories/examples/DropdownMenuOnCloseExample.js
packages/DropdownMenu/stories/examples/DropdownMenuWithCustomClassExample.js

I added two things to `<DropdownMenu />`:
1. You can now pass in an `onClose` prop that is fired after the component is closed.  I need this so I can change the active state of the trigger that opened it.
2. You can now add a `<DropdownMenu.Content />` as a child of `<DropdownMenu>` to add props (e.g. a "className") to the internal `Popover.Card`:
I need this so I can target the Popover for style changes, i.e. remove this gap:

Uxd 464 expose onclose and card

---

packages/FormElement/CHANGELOG.md
packages/FormElement/src/FormElement.styles.js
packages/FormElement/src/components/Content/Content.js
packages/FormElement/src/components/Content/Content.styles.js
packages/FormElement/src/components/Description/Description.styles.js
packages/FormElement/src/components/ErrorMessage/ErrorMessage.styles.js

1. Ensure formElement has margins applied so that application css won't override. (eg in the case of a fieldset)
2. Cleanup margins on subcomponents
http://storybooks.highbond-s3.com/paprika/uxd-478-formElement-margins

Uxd-478 form element margins

---

packages/ExternalLink/CHANGELOG.md
packages/ExternalLink/stories/examples/LayoutExamples.js
packages/ExternalLink/stories/examples/Showcase.js
packages/RawButton/stories/examples/Showcase.js

- fix knob label for a11yText
http://storybooks.highbond-s3.com/paprika/UXD-485-knob-change

UXD-485 fix knob label

---

packages/OverflowMenu/package.json
packages/OverflowMenu/src/OverflowMenu.js
packages/OverflowMenu/stories/OverflowMenu.stories.js
packages/OverflowMenu/stories/examples/AutoFocusExample.js
yarn.lock

1. Dont focus on first element when expand OverflowMenu using mouse
2. Dont focus on OverflowMenu trigger when exit OverflowMenu by pressing the Tab key.
This is related to this ticket: https://aclgrc.atlassian.net/browse/UXD-464
The two issues can be seen here: https://github.com/acl-services/paprika/issues/794
http://storybooks.highbond-s3.com/paprika/issue-794--overflow-focus
Before can be seen here: https://github.com/acl-services/paprika/issues/794
After:

Issue 794  overflow focus

---

packages/Radio/CHANGELOG.md
packages/Radio/src/components/Group/Group.js
packages/Radio/stories/Radio.examples.stories.js
packages/Radio/stories/Radio.stories.js
packages/Radio/stories/Radio.stories.styles.js
packages/Radio/stories/examples/Controlled.js
packages/Radio/stories/examples/Showcase.js
packages/Radio/stories/examples/Uncontrolled.js

The `<Radio.Group>` has a `size` prop that should be passed along to its `<Radio>` `children`.
- `<Radio.Group>` was not including `size` when it did `React.cloneElement()`.
- `A11yText` prop was removed from `<Radio.Group>` – it was being implemented incorrectly as `aria-labelledby`, and had no effect.  The radio group needs to get a label from a parent `<FormElement hasFieldSet>`. 
- This _would_ be a `MAJOR` breaking change normally, but because it was already "broken", this can remain a `PATCH` update.
- Fixed the `Showcase` story, converted all stories to CSF, and split the examples in  the `Controlled` story into `Controlled` and `Uncontrolled` example stories.
http://storybooks.highbond-s3.com/paprika/RAPRM-926--fix-radio-button/?path=/story/forms-radio--showcase …

RAPRM-926  Fix Radio.Group size prop 🐐

---

packages/StatusTracker/CHANGELOG.md
packages/StatusTracker/src/components/Point/Point.js
packages/StatusTracker/src/components/Point/Point.styles.js

- Fixed min-width for popover
- Fixed aria-describedby
- Fixed button alignment
http://storybooks.highbond-s3.com/paprika/UXD-613-fix-status-tracker-ui/?path=/story/buttons-statustracker--showcase
http://storybooks.highbond-s3.com/paprika/UXD-613-fix-status-tracker-ui

fix(StatusTracker): UXD-613 fixed some minor styling and a11y issues

---

packages/OverflowMenu/CHANGELOG.md
packages/OverflowMenu/src/OverflowMenu.js
packages/OverflowMenu/test/overflowMenu.spec.js

Fix passing dynamic props to Confirmation on update
`renderConfirmation` state gets updated only when you click on the Item: https://github.com/acl-services/paprika/blob/4d84b80efcf86d70066fe4dd113a1f6f2a5b5dc0/packages/OverflowMenu/src/OverflowMenu.js#L183 This makes it impossible to use dynamic props in `Confirmation` component (e.g. `isPending`), since they never get updated in state until the next click.
This PR replaces `renderConfirmation` state with reference and adds explicit updates when required.
See discussion in https://wegalvanize.slack.com/archives/CB3QRPDJ4/p1607629290311200
http://storybooks.highbond-s3.com/paprika/FS-564-fix-OverflowMenu-rerendering
https://aclgrc.atlassian.net/browse/FS-564

fix(OverflowMenu): FS-564 pass dynamic props to Confirmation on update

---

packages/ListBox/README.md
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/WithTags/WithTags.js

Update which proptypes are allowed in ListBoxWithTags

fix(ListBox): UXD-590 Update which proptypes are allowed in ListBoxWithTags

---

.semaphore/semaphore.yml

Trying to fix and improve cypress + semaphore after reaching semaphore support
> Thanks for reaching out. I'll do my best to help you out.
> 
> It seems this issue is caused by a shortage of memory. The job might have run out of memory right before it failed. Here are a few workarounds I'd like to propose:
>
> 1. Debugging the issue by launching an SSH session into the job.
> 2. Using a bigger machine such as e1-standard-4 or e1-standard-8 since having access to more resources should help.
> 3. Using a swap file. Our machines are running on RAM allocated disks. As the disk and RAM have the same performance, you can allocate swap space in the job and increase the memory. To resize the disk in > favor of RAM, you can add the following to the top of your job:
>
> sudo swapoff -a && sudo …

chore(Paprika): trying to fix semaphore issue )UXD-704

---

.semaphore/semaphore.yml
packages/DynamicHyperlink/src/DynamicHyperlink.scss

Links should break onto a second line as needed
Also change a semaphore setting that is supposed to increase our RAM (https://docs.semaphoreci.com/ci-cd-environment/machine-types/#linux-machine-types), so tests stop failing for reasons beyond our control.

Pdtvt 685  multi line

---

packages/FormElement/src/components/Label/Label.styles.js

See screenshots
http://storybooks.highbond-s3.com/paprika/FS-976-fix-margins-for-form-element-label
Before:
After:
https://aclgrc.atlassian.net/browse/FS-976

fix(FormElement): FS-976 Display FormElement.Label as block

---

packages/DynamicHyperlinkTransformer/src/DynamicHyperlinkTransformer.js
packages/DynamicHyperlinkTransformer/src/DynamicHyperlinkTransformer.scss
packages/DynamicHyperlinkTransformer/stories/tests/Screener.js

Don't underline the right-hand-side of the cards on hover. Note: they are still clickable links, as everything is under a link..
http://storybooks.highbond-s3.com/paprika/pdtvt-784--no-underline

chore(DynamicHyperlinkTranslator): PDTVT-784 Tweak link styles.

---

packages/L10n/src/locales/en.yml

Remove obsolete translation keys. This was just an earlier oversight.

chore(ActionBar): UXD-684 remove obsolete translation keys

---

.changeset/nine-steaks-rescue.md
packages/CollapsibleCard/src/CollapsibleCard.js
packages/CollapsibleCard/src/components/Group/Group.js
packages/CollapsibleCard/src/components/Header/Header.styles.js

We need to support custom `position` so even though the CollapsibleCard is in the `middle` between others in the DOM, but visually it's the `last`
- Support `position` to be passed in 
- Export `position` values
- Remove `uuid()` keys on CollapsibleCard
- Small css adjustment

feat(CollapsibleCard): UXD-963 support position to be passed in

---

.changeset/four-bears-dream.md
packages/Popover/src/components/Content/Content.js
packages/Popover/src/components/Trigger/Trigger.js
packages/Popover/stories/examples/StateValue.js

Follow on pr from https://github.com/acl-services/paprika/pull/975
This PR addresses some incorrect and missing aria attributes on the Popover Trigger when used as a tooltip or just as a popover
http://storybooks.highbond-s3.com/paprika/uxd-1007-fix-popover-tooltip-accessibility

Uxd 1007 fix popover tooltip accessibility

---

.changeset/tender-flies-pretend.md
packages/Tabs/src/Tabs.js

Set initial `focusIndex` to selected tab index, or first tab index if no tab is selected.
- Currently if no tab is initially selected (active) then all tabs have `tabindex="-1"` and the `<Tabs>` component is inoperable by keyboard. 
http://storybooks.highbond-s3.com/paprika/UXD-982--fix-initial-focus/?path=/story/navigation-tabs-backyard-tests--keyboard
Compare with current behaviour:
https://paprika.highbond.com/?path=/story/navigation-tabs-backyard-tests--keyboard
https://aclgrc.atlassian.net/browse/UXD-982

UXD-982 Fix initial focus index for Tabs 🐐

---

.changeset/thin-windows-arrive.md
packages/ProgressAccordion/src/ProgressAccordion.js
packages/ProgressAccordion/src/components/Item/Item.js
packages/ProgressAccordion/src/components/Item/Item.styles.js
packages/ProgressAccordion/src/components/NavItem/NavItem.js
packages/ProgressAccordion/src/components/NavItem/NavItem.styles.js
packages/ProgressAccordion/src/components/NavItem/index.js
packages/ProgressAccordion/src/kinds.js
packages/ProgressAccordion/stories/examples/Nav.js

I made a different sub-component so the ProgressAccordion is easier to use as a nav.
Made some style tweaks to it (black when complete and grey when incomplete, changed hover cursor if theres no click action).
No one is using this component as a nav, so just did it as a patch.

Pdtvt 1034  progress accordion nav tweaks

---

.changeset/young-tools-wink.md
packages/Breadcrumbs/src/Breadcrumbs.js
packages/Breadcrumbs/stories/Breadcrumbs.tests.stories.js
packages/Breadcrumbs/stories/examples/RerenderBreadcrumbs.js
packages/Breadcrumbs/tests/Breadcrumbs.cypress.js

Forgot to update the internal state based on component changes/re-render
test here: http://storybooks.highbond-s3.com/paprika/ASM-1154-fix-breadcrumb-rerender?path=/story/breadcrumbs-tests--rerender-breadcrumbs

fix(Breadcrumbs): ASM-1154 show expand button when rerender

---

.changeset/bright-readers-reflect.md
packages/DataHeader/package.json
packages/DataHeader/src/DataHeader.styles.js
packages/DataHeader/stories/DataHeaderWithLongTitle.datagrid.stories.js

fix css issues with long text in data header
test here:  http://storybooks.highbond-s3.com/paprika/UXD-1068-data-header-csss/?path=/story/table-dataheader--data-grid-with-long-title-example
Before:
After:
http://storybooks.highbond-s3.com/paprika/UXD-1068-data-header-csss

fix(DataHeader): UXD-1068 fix css issues with long text

---

.changeset/late-seas-guess.md
packages/ActionBar/README.md
packages/ActionBar/src/components/ColumnsArrangement/ColumnsArrangement.js
packages/ActionBar/src/hooks/useColumnsArrangement/useColumnsArrangement.js
packages/ActionBar/stories/Actionbar.stories.js
packages/ActionBar/stories/examples/ButtonTrigger.js
packages/ActionBar/stories/examples/CustomButton.js
packages/ActionBar/stories/examples/WithLocalStorageEnabled.js
packages/ActionBar/tests/cypress/ActionBar.cypress.js
packages/DataGrid/stories/DataGrid.resize.stories.js

This PR is for using localStorage to save the show/hide states in `useColumnsArrangement` hook. There'll be a follow-up PR to save the orders of columns.
Saving in localStorage will be only activated, when you pass in the `localStoragePrefix` when you use the hook.
For developers who are not using the hook, you can implement that by yourself.
Try here: http://storybooks.highbond-s3.com/paprika/UXD-1086-support-using-localStorage/?path=/story/table-actionbar-examples--with-localstorage-enabled
**_[BREAKING CHANGES]_**
This PR also changes the way of passing parameters to `useColumnsArrangement` hook.
Before:
```jsx
const {orderedColumnIds, ...} = useColumnsArrangement(
defaultOrderedColumnIds, // string[], required
disabledColumnIds  // string[]
);
```
After:
```jsx
const …
```

UXD-1086 support local storage in useColumnsArrangement

---

.changeset/silent-islands-fold.md
packages/ActionBar/src/hooks/useColumnsArrangement/useColumnsArrangement.js

forgot to fallback to the passed in hidden columns value if the cache is not there

Uxd 1086 Bug fix for saving show/hide columns in localStorage

---

.changeset/nasty-ads-rest.md
packages/DataHeader/src/DataHeader.styles.js

- Icon color changed to #717171
- Focusing ring on the ... button 
http://storybooks.highbond-s3.com/paprika/UXD-1091-data-header-small-fix/?path=/story/table-dataheader--data-grid-with-long-title-example

Uxd 1091 data header small fix

---

.changeset/spicy-lizards-film.md
packages/StatusTracker/src/StatusTracker.styles.js
packages/StatusTracker/src/components/Point/Point.styles.js

- update status tracker with new colours
http://storybooks.highbond-s3.com/paprika/UXD-1122-update-status-tracker-colours

UXD-1122 chore(StatusTracker): new colours

---

.changeset/moody-snails-live.md
packages/Popover/README.md
packages/Popover/src/Popover.js
packages/Popover/src/components/Content/Content.js
packages/Popover/stories/Popover.examples.stories.js
packages/Popover/stories/examples/Multiple.js
packages/Popover/stories/sandbox/FocusTest.js

Don't allow multiple `<Popovers>` to be open at the same time.
- Ensure `<Popover.Content>` receives focus after opening so its `onBlur` event will cause it to close.
- **BONUS:** Ensure proper `tab` focus order when `<Popover.Content>` has no focussable elements.
http://storybooks.highbond-s3.com/paprika/UXD-1128--popover-bugs/?path=/story/messaging-popover-examples--multiple-story
https://aclgrc.atlassian.net/browse/UXD-1128

UXD-1128  Squash two Popover bugs 🐐

---

.changeset/chilly-spoons-march.md
packages/BuildTranslations/package.json

Used `"@babel/runtime-corejs2"` to build, but missing it in the dependency list

fix(BuildTranslations): UXD-1170 fix missing dependency issue

---

.changeset/ninety-berries-hide.md
.changeset/wise-waves-look.md
packages/ListBox/src/ListBox.js
packages/ListBoxWithTags/src/ListBoxWithTags.js
packages/ListBoxWithTags/stories/ListBoxWithTags.examples.stories.js
packages/ListBoxWithTags/stories/examples/SpreadingSubComponents.js

Simply allowed to spread down properties to different subcomponent from ListBoxWithTags to ListBox

feature(ListBoxWithTags): UXD-1160 spreading props on listBoxWithTags

---

packages/Filter/README.md
packages/Filter/stories/Hooks/Hooks.js
packages/Filter/stories/MockServer/MockServer.js

I was going to add the ability to force `AND` or `OR` and prevent the user from being able to switch... but turns out that functionality is already in there.  So instead I updated the docs to make it more clear.

chore(Filter): UXD-1203 Update docs, highlighting that 'operator' can be forced

---

packages/ActionBar/src/hooks/useColumnsArrangement/useColumnsArrangement.js

https://github.com/acl-services/paprika/pull/897
immer v8 doesn't support `Set` and `Map` by default anymore, so revert it back to use array

chore(ActionBar): ISSUE-XXX fix immer upgrade issue

---

Dockerfile.build

Paprika storybook isnt deploying. Checked with Samson and build pipeline has this error:
```
[1/5] Validating package.json...
error @paprika/paprika@: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
time="2021-06-06T03:11:11.861576915Z" level=info msg="shim reaped" id=23f7a7e6706bbcace889dcb995c5430074757685ea86979053ed85513380fe04 
time="2021-06-06T03:11:11.871614657Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
The command '/bin/sh -c yarn' returned a non-zero code: 1
```
Probably caused by updating node version in package.json 4 weeks ago: …

chore(Semaphore): UXD-1150 Update node version for semaphore

---

.changeset/kind-forks-begin.md
.changeset/stupid-gifts-bathe.md
packages/ListBox/src/components/Filter/Filter.js
packages/ListBox/src/imperative/imperative.js
packages/ListBoxWithTags/src/ListBoxWithTags.js

After selecting an option in  `<ListBoxWithTags>`, the option is removed from the list and the 'focus' is lost from the ListBox.
As a result, if the user tries to dismiss the popover list by clicking outside of it, it will not be dismissed, until the user refocuses the ListBox (i.e. click on the filter input). 
- Add new imperative functions for focusing in ListBox and ListBox.Filter. This allows to focus a listbox option by its index in the option list.
- ListBoxWithTags will now remember the last selected option, and try to update the focus upon render (since the component rerenders every time you select an option). If no options are left, then it will default to focusing on the filter input.
- If the user uses the filter and selects an option, it will be defaulted to focus on the …

fix(ListBoxWithTags): ADM-1775 Fix ListBoxWithTags focus after selecting an option

---

.changeset/smooth-pigs-promise.md
packages/ListBoxWithTags/src/ListBoxWithTags.js

In `<UserLookup>`, the underlying `<ListBoxWithTags>` could include options that are 'group dividers'. As a result, if you selected the last option in the list as well as its 'group', it will throw an error since it tries to refocus on the second to last item (which is the 'group divider', and since that disappears as well and the index becomes undefined)
http://storybooks.highbond-s3.com/paprika/ADM-1775-patch-fix-listboxwithtags-focus
**Issue seen in `<UserLookup>`:**
**Expected behaviour (it is fixed in UserLookup already when it uses the underlying ListBox instead of ListBoxWithTags):**
Followup fix to https://github.com/acl-services/paprika/pull/1080

ADM-1775 Fix ListBoxWithTags refocus on an undefined option after selecting last option

---

.changeset/twenty-rats-hug.md
packages/ListBox/src/ListBox.js
packages/ListBox/src/components/Content/Content.js
packages/ListBox/src/index.js
packages/ListBox/test/specs/single/ListBox.single.spec.js

There are times where consumers (such as `UserLookup`) would need to adjust or customize the styling of the listbox popover content. This CL addresses to expose the `<ListBox.Content>` subcomponent to spread props down.
http://storybooks.highbond-s3.com/paprika/ADM-1844-expose-listbox-content-api
https://aclgrc.atlassian.net/browse/ADM-1844

feat(ListBox): ADM-1844 Expose ListBox.Content to spread props.

---

.changeset/pink-pots-cough.md
packages/CopyInput/src/CopyInput.js
packages/CopyInput/src/components/Popover/Popover.js
packages/CopyInput/src/components/Popover/index.js
packages/CopyInput/stories/variations/Variations.js

https://aclgrc.atlassian.net/browse/RAPRM-2168-variables-takeover-copy-input
Adding support for Popover shell, as needed in variablesTakeover, specifically need for `Zindex` and `scrollContainer` props. Also, given reports of issues with the copy input, we have decided to opt into using the `Clipboard` API, as it is async, it has better performance when copying larger inputs, and also allows copying of variables (which would be preferred in our case) (and possibly copy of images may be easier in future)
https://web.dev/async-clipboard/
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
Since `Clipboard` is not supported in IE, we are using the old logic as a safety net if the Clipboard is not supported.
Note: Permission must be requested for read events (**we use write**) e.g. …

RAPRM-2168 variables takeover copy input

---

.changeset/strange-mails-tie.md
packages/Sortable/CHANGELOG.md
packages/Sortable/src/components/SortableItem/SortableItem.js

Render remove button as a `<span>` instead of a `<button>` to make it more resilient to global CSS.
Ticket : https://aclgrc.atlassian.net/browse/UXD-1348

UXD-1348 fix(Sortable): add isSemantic false to sortable.item delete button

---

.changeset/fluffy-eels-hope.md
packages/Breadcrumbs/src/components/Link/Link.js
packages/Breadcrumbs/src/components/Link/LinkTooltipContentPropsCollector.js
packages/Breadcrumbs/stories/examples/AllVariations.js

Allow passing additional props to the Breadcrumb Link Tooltip (Popover.Content).
This is required to at least be able to change/set the zIndex on it as it is currently rendering behind some other UI in it's implementation in Visualizer
http://storybooks.highbond-s3.com/paprika/uxd-1417-breadcrumb-link-tooltip-additional-props

UXD-1417 breadcrumb link tooltip additional props

---

packages/Switch/src/Switch.styles.js

https://aclgrc.atlassian.net/browse/UXD-1501
Removed the square border around the switch when navigated through tab
Adjusted the selector to be more specific when focused.
After:
Before:
https://aclgrc.atlassian.net/browse/UXD-1500

UXD-1501 Removed extra focused border of the switch component

---

.changeset/selfish-olives-share.md
packages/CopyInput/src/CopyInput.styles.js
packages/CopyInput/stories/variations/Variations.js

Ensure `<CopyInput hasInputContainer={false}>` hides input field.
- Specificity of CSS was increased to fix an issue with the way `styled-components` applies styles in consuming app.
http://storybooks.highbond-s3.com/paprika/RAPRM-2465--copyinput-hide-input-fix
https://aclgrc.atlassian.net/browse/RAPRM-2465

RAPRM-2465 Ensure CopyInput hides input when hasInputContainer is false 🐐

---

.changeset/short-parents-try.md
packages/ButtonGroup/src/ButtonGroup.js
packages/ButtonGroup/src/ButtonGroup.styles.js
packages/ButtonGroup/stories/examples/Sandbox.js

Before (left edge is square):
After (left edge is round):

Pdtvt 1689  button group single

---

.changeset/pretty-hats-divide.md
packages/Breadcrumbs/src/Breadcrumbs.styles.js
packages/Breadcrumbs/src/components/ExpandButton/ExpandButton.styles.js
packages/Breadcrumbs/src/components/Link/Link.js
packages/Breadcrumbs/src/components/Link/Link.styles.js
packages/Breadcrumbs/stories/Breadcrumbs.examples.stories.js
packages/Breadcrumbs/stories/Breadcrumbs.stories.js
packages/Breadcrumbs/stories/examples/Alignment.js
packages/Breadcrumbs/stories/examples/Variations.js

Ensure that the Breadcrumb links consistently align vertically with other elements on the page.
Related PR https://github.com/acl-services/sriracha/pull/896
- Easier said than done! The larger the font of external elements, the more padding within the typeface will cause a misalignment.  
- This PR will ensure that the container elements align, whether a native `<Breadcrumb.Link>` is used, or whether it is customized and transformed into a different type of HTML element via the `as` prop.
- Also refactored the coding style of the `styles.js` files to align with current conventions. 
- Added a new Storybook story, `Alignment` to illustrate the consistency between types of elements and inconsistency when a large font is used (see below). …

UXD-1592  Alignment of Breadcrumbs 🐐

---

.changeset/chilly-moons-buy.md
packages/Breadcrumbs/src/Breadcrumbs.js
packages/Breadcrumbs/stories/Breadcrumbs.examples.stories.js
packages/Breadcrumbs/stories/examples/Dynamic.js
packages/Breadcrumbs/stories/examples/Variations.js

Support `null` children and children wrapped in `<React.Fragments>`.
- Solves for use cases where breadcrumb links are conditionally rendered.
- use `extractChildren()` helper to filter `children` to only `<Breadcrumb.Link>` children.
- Added two examples in the Storybook Variations story.
http://storybooks.highbond-s3.com/paprika/UXD-1717--filter-breadcrumb-children
https://aclgrc.atlassian.net/browse/UXD-1717
https://github.com/acl-services/acl-exception/pull/8747/files#r750731213

UXD-1717  Filter Breadcrumb children  🐐

---

.changeset/grumpy-cherries-count.md
packages/Icon/svgr.config.js

Ensure that icons scale with browser zoom, specifically with Safari.
- Added `height` and `width` CSS back to svg props in `svgr.config`
- Reverts a change in https://github.com/acl-services/paprika/pull/1158
- Companion PR in `wasabicons`: https://github.com/acl-services/wasabicons/pull/63
http://storybooks.highbond-s3.com/paprika/UXD-1901--fix-icon-scaling-safari/?path=/story/display-icon--showcase-story
Safari @ 50% zoom
[_relevant Jira ticket / GitHub issues_
](https://aclgrc.atlassian.net/browse/UXD-1901)

UXD-1901 Fix icon scaling in Safari 🐐

---

.changeset/rotten-forks-return.md
packages/ButtonGroup/src/components/Item/Item.styles.js

[FS-2620: [FE] Remove gap between buttons in button group in Safari browser (Paprika)](https://aclgrc.atlassian.net/browse/FS-2620)

fix(ButtonGroup): FS-2620 removed gap in Safari

---

.changeset/red-files-guess.md
packages/Radio/src/components/Group/Group.js

Added useImperativeHandle hook so user can update the checkedIndex via ref
Thanks Allison for the instruction!!
In application:
[_relevant Jira ticket / GitHub issues_](https://aclgrc.atlassian.net/browse/UXD-1934)

fix(Radio): UXD-1934 added updateCheckIndex

---

.changeset/shiny-mayflies-play.md
packages/ActionBar/package.json
packages/Filter/package.json
yarn.lock

Bump all instances of ImmerJS to >= 9.0.6 to resolve CVE-2021-3757
- Bump immer in ActionBar and Filter to immer@9.0.12 (latest)
- Patch version of ActionBar and Filter in docs
Ticket: https://aclgrc.atlassian.net/browse/SNP-2319

SNP-2319 bump immer to resolve CVE-2021-3757

---

.changeset/fresh-oranges-pull.md
packages/Overlay/CHANGELOG.md
packages/Overlay/src/Overlay.js
packages/Overlay/src/index.d.ts
packages/Takeover/README.md
packages/Takeover/src/Takeover.js
packages/Takeover/src/Takeover.styles.js
packages/Takeover/src/components/Header/Header.js
packages/Takeover/src/components/Header/Header.styles.js
packages/Takeover/src/index.d.ts
packages/Takeover/stories/Takeover.examples.stories.js
packages/Takeover/stories/Takeover.stories.js
packages/Takeover/stories/TakeoverStory.js

Update Takeover component base on the new design guideline.
ticket:
https://aclgrc.atlassian.net/browse/UXD-1978
https://aclgrc.atlassian.net/browse/UXD-1979
https://aclgrc.atlassian.net/browse/UXD-1981
- need to update the overlay component so the backdrop isn't clickable.
Will run `yarn changeset` after footer is done.
http://storybooks.highbond-s3.com/paprika/UXD-1978-Takeover-header-style-updates

UXD-1978 takeover header style updates

---

.changeset/quick-boxes-relate.md
packages/OverflowMenu/src/components/Trigger/Trigger.js

Fix an import of `@paprika/button` in `<OverflowMenu.Trigger>` subcomponent.
- Mistakenly broken in this PR https://github.com/acl-services/paprika/pull/1235/files#diff-f3b0ef67cf665a5cce23c1ae77d8dccaa87149196628080c5a1997c2a3d76fecL4
- Error seen in consuming app:
```
./node_modules/@paprika/overflow-menu/lib/components/Trigger/Trigger.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/@paprika/Button/lib/button'.
```
https://aclgrc.atlassian.net/browse/RNG-372

RNG-372 Fix broken import in OverflowMenu.Trigger 🐐

---

.changeset/spicy-dots-press.md
packages/Uploader/src/components/File/File.js
packages/Uploader/stories/Uploader.stories.js

https://aclgrc.atlassian.net/browse/UXD-2022
Fix Uploader `onError` being called unnecessarily

Uxd 2022 uploader fix on error

---

.changeset/famous-queens-switch.md
packages/Uploader/src/Uploader.js

stop reseting input value in uploader component

fix(Uploader): stop reseting input value in uploader component

---

.changeset/wise-cows-repair.md
packages/Uploader/src/Uploader.js
packages/Uploader/src/useDragAndDropEvents.js

When users upload files through drag&drop, the input `onChange` event won't be triggered as normal. So manually assign the `files` to `files` property on the html input element inside the uploader

fix(Uploader): assign files on the html input when drag drop

---

.changeset/plenty-fans-draw.md
packages/Uploader/src/Uploader.js

Using `DataTransfer` to convert the original FileList to a filtered FileList

fix(Uploader): Fixed drag&drop issue when canChooseMultiple is false

---

yarn.lock

Fix `moment` CVE. It's independent of LP fix. addressing it as well since it was raised 👍 
https://aclgrc.atlassian.net/browse/ADM-3039
- Ran yarn why moment to identify the dependency tree
- Since is not directly added to any package, I deleted the blocks in `yarn.lock` and I ran `yarn install` again.
- The reinstall adds required versions hoisted under the latest update `2.29.3`
- Verified with yarn audit the CVE alert is gone
_relevant Jira ticket / …

fix(AddressMomentCVE): reinstall moment to bump hoisted versions 

---

.changeset/tall-turkeys-dance.md
packages/Card/src/components/Content/Content.js
packages/Card/src/components/Footer/Footer.js
packages/Card/src/components/Metadata/Metadata.js
packages/Card/src/components/Text/Text.js
packages/Card/src/components/Title/Title.js
packages/Card/src/index.d.ts

Fix `<Card>` typings to include subcomponents in the `Card` namespace.
- Fixed subcomponent `displayNames` and regenerated typings files by running `generateTypeDefinitionsForJS` script
https://aclgrc.atlassian.net/browse/UXD-2116

UXD-2116 Fix Typescript definition for Card subcomponents 🐐

---

.changeset/sharp-bees-carry.md
packages/BuildTranslations/package.json
yarn.lock

Make the runtime-corejs2 version fixed, in case changes from their side breaks the npx job in our apps

fix(BuildTranslation): UXD-2120 fixed the runtime-corejs2 version

---

.changeset/bright-beans-cry.md
packages/DateInput/src/DateInput.js

```jsx
<DatePicker>
<DatePicker.Input hasClearButton />
</DatePicker>
```
This code currently doesn't work (crashes)
It will be fixed by this PR.

fix(DateInput): FS-3112 Support of `hasClearButton`

---

.changeset/warm-tools-reply.md
packages/Modal/src/components/FocusLock/FocusLock.js
packages/Overlay/src/Overlay.js
packages/Takeover/src/components/FocusLock/FocusLock.js

Paprika modal components – <Modal>, <Takeover> and <Panel> (with <Panel.Overlay>) – are not allowing focus to remain in the Pendo tagging overlay’s  <input> fields.  This is creating a very annoying experience when trying to tag UI elements for usage tracking.
http://storybooks.highbond-s3.com/paprika/UXD-2122-allow-pendo-elements-to-steal-focus

feat(ReactFocusLock): allow pendo elements to steal focus

---

.changeset/five-bags-refuse.md
packages/ListBoxWithTags/src/ListBoxWithTags.js

`ListBoxWithTags` crashes after selecting option and typing something in search box.
Reason: stale value in `lastSelectedOption`. This value references non-existing option (because after search there can be completly different list of options)

fix(ListBoxWithTags): FS-3112 Fix focus after select

---

.changeset/weak-brooms-pull.md
packages/CollapsibleCard/src/CollapsibleCard.js
packages/CollapsibleCard/stories/examples/ControlledAndUncontrolled.js

fix `CollapsibleCard` not controllable issue https://aclgrc.atlassian.net/browse/UXD-2135
I know this is not a proper fix 😬  
Basically the CollapsibleCard will expand/collapse every time when users click on the card header, even the prop `isCollapsed` doesn't change
A proper fix might be always respecting the value of `isCollapsed` prop, if it's not `null` we just don't use the internal state. However that would be a major bump, it might break somewhere in our platform if the consumer uses `isCollapsed`
So I added some comments and example to demonstrate how to skip the internal state update. I've also checked with our designer, this use case won't be common anyway, we should always let the user expand/collapse the card. We can convert this PR to an issue if we don't want to fix. 
Can be …

fix(CollapsibleCard): fix not controllable issue

---

.changeset/kind-lemons-train.md
packages/DataTable/package.json
packages/DataTable/src/helpers/rowHeightHelper.ts
yarn.lock

Ticket: https://diligentbrands.atlassian.net/browse/TW-3363
There is a security issue with the DataTable component in that non sanitized data is rendered to the Dom via the VariableList subcomponent, row height calculations.
This pr sanitizes that html
http://storybooks.highbond-s3.com/paprika/tw-3363-sanitize-data-table-html

fix(DataTable): TW-3363 Sanitize html rendered in DataTable VariableList

---

.gitignore
packages/FormElement/README.md
packages/FormElement/src/FormElement.js
packages/FormElement/src/components/Help/Help.js
packages/FormElement/src/components/Label/Label.js
packages/FormElement/src/index.d.ts
packages/FormElement/stories/FormElement.examples.stories.js
packages/FormElement/stories/examples/LabelWithHelpInsidePanel.js
packages/FormElement/tests/FormElement.cypress.js

- fix zIndex when form inside Model or Panel
before:
after:
https://diligentbrands.atlassian.net/browse/FS-4709

FS-4709 FormElement.Help component fix zIndex when component inside Popover

---

.changeset/funny-flowers-prove.md
packages/DataGrid/src/DataGrid.js

Fix header scrolling in DataGrid
BEFORE: (the header is not being scrolled horizontally, while the table body is scrolled)
AFTER: (the header is scrollable)
https://diligentbrands.atlassian.net/browse/FS-4981
https://diligentbrands.atlassian.net/browse/FS-4985

FS-4985: Fix DataGrid scroll

---

.changeset/good-papayas-know.md
packages/Calendar/tests/DateRangeCalendar.cypress.js
packages/Calendar/tests/SingleDateCalendar.cypress.js
packages/DatePicker/test/DatePicker.cypress.js
packages/L10n/src/useI18n.js
packages/L10n/src/useI18n.spec.js

Previously the _forEach_ on `paprikaLocales` acted as a hidden filter on the merge of locales. Resulting in missing `customLocales` unless they are also part of `paprikaLocales`. This was noticed when trying to use the new `nl` locale in a package that had not published the `nl` assets.
To avoid this hidden filter. This change makes the merge work on the unique set of languages keys from both params (`paprikaLocales`, `customLocales`) resulting in a full merge. Also adds unit tests. …

fix(l10n): Improve locale merging technique
